const koreanDatabase = [
  // --- Easy: Pronouns, Numbers, Colors, Basics ---
  { "word": "나", "pos": "pron.", "trans": "我 (非敬語)", "example": "나는 학생이야.", "exampleTrans": "我是學生。", "diff": "easy" },
  { "word": "저", "pos": "pron.", "trans": "我 (敬語)", "example": "저는 학생이에요.", "exampleTrans": "我是學生。", "diff": "easy" },
  { "word": "우리", "pos": "pron.", "trans": "我們", "example": "우리 같이 가요.", "exampleTrans": "我們一起去吧。", "diff": "easy" },
  { "word": "하나", "pos": "num.", "trans": "一", "example": "사과 한 개 주세요.", "exampleTrans": "請給我一個蘋果。", "diff": "easy" },
  { "word": "둘", "pos": "num.", "trans": "二", "example": "사과가 두 개 있어요.", "exampleTrans": "有兩顆蘋果。", "diff": "easy" },
  { "word": "셋", "pos": "num.", "trans": "三", "example": "사람이 세 명이에요.", "exampleTrans": "有三個人。", "diff": "easy" },
  { "word": "넷", "pos": "num.", "trans": "四", "example": "강아지 네 마리가 있어요.", "exampleTrans": "有四隻小狗。", "diff": "easy" },
  { "word": "다섯", "pos": "num.", "trans": "五", "example": "손가락이 다섯 개예요.", "exampleTrans": "手有五根指頭。", "diff": "easy" },
  { "word": "여섯", "pos": "num.", "trans": "六", "example": "여섯 시에 만나요.", "exampleTrans": "六點見面吧。", "diff": "easy" },
  { "word": "일곱", "pos": "num.", "trans": "七", "example": "일주일은 7일이에요.", "exampleTrans": "一週有七天。", "diff": "easy" },
  { "word": "여덟", "pos": "num.", "trans": "八", "example": "여덟 시까지 오세요.", "exampleTrans": "請在八點前過來。", "diff": "easy" },
  { "word": "아홉", "pos": "num.", "trans": "九", "example": "아홉 명의 학생이 있어요.", "exampleTrans": "有九個學生。", "diff": "easy" },
  { "word": "열", "pos": "num.", "trans": "十", "example": "열 개를 샀어요.", "exampleTrans": "買了十個。", "diff": "easy" },
  { "word": "빨간색", "pos": "n.", "trans": "紅色", "example": "빨간색 사과가 맛있어요.", "exampleTrans": "紅色的蘋果很好吃。", "diff": "easy" },
  { "word": "파란색", "pos": "n.", "trans": "藍色", "example": "하늘이 파란색이에요.", "exampleTrans": "天空是藍色的。", "diff": "easy" },
  { "word": "노란색", "pos": "n.", "trans": "黃色", "example": "노란색 바나나를 좋아해요.", "exampleTrans": "我喜歡黃色的香蕉。", "diff": "easy" },
  { "word": "초록색", "pos": "n.", "trans": "綠色", "example": "숲은 초록색으로 가득해요.", "exampleTrans": "森林充滿了綠色。", "diff": "easy" },
  { "word": "검은색", "pos": "n.", "trans": "黑色", "example": "검은색 고양이가 지나가요.", "exampleTrans": "一隻黑色的貓經過。", "diff": "easy" },
  { "word": "하얀색", "pos": "n.", "trans": "白色", "example": "하얀색 눈이 내려요.", "exampleTrans": "白色的雪落了下來。", "diff": "easy" },
  { "word": "어머니", "pos": "n.", "trans": "母親", "example": "우리 어머니는 요리를 잘하세요.", "exampleTrans": "我媽媽很會做飯。", "diff": "easy" },
  { "word": "아버지", "pos": "n.", "trans": "父親", "example": "아버지는 회사에 가셨어요.", "exampleTrans": "爸爸去公司了。", "diff": "easy" },
  { "word": "형", "pos": "n.", "trans": "哥哥 (男稱)", "example": "우리 형은 키가 커요.", "exampleTrans": "我哥哥長得很高。", "diff": "easy" },
  { "word": "누나", "pos": "n.", "trans": "姐姐 (男稱)", "example": "누나가 정말 예뻐요.", "exampleTrans": "姐姐很漂亮。", "diff": "easy" },
  { "word": "오빠", "pos": "n.", "trans": "哥哥 (女稱)", "example": "우리 오빠는 군인이에요.", "exampleTrans": "我哥哥是軍人。", "diff": "easy" },
  { "word": "언니", "pos": "n.", "trans": "姐姐 (女稱)", "example": "언니와 쇼핑하러 가요.", "exampleTrans": "和姐姐去購物。", "diff": "easy" },
  { "word": "물", "pos": "n.", "trans": "水", "example": "시원한 물을 마시고 싶어요.", "exampleTrans": "我想喝涼水。", "diff": "easy" },
  { "word": "밥", "pos": "n.", "trans": "飯 / 正餐", "example": "밥 먹었어?", "exampleTrans": "吃過飯了嗎？", "diff": "easy" },
  { "word": "빵", "pos": "n.", "trans": "麵包", "example": "이 빵은 정말 맛있어요.", "exampleTrans": "這麵包真的很好吃。", "diff": "easy" },
  { "word": "우유", "pos": "n.", "trans": "牛奶", "example": "매일 우유를 마셔요.", "exampleTrans": "每天喝牛奶。", "diff": "easy" },
  { "word": "학교", "pos": "n.", "trans": "學校", "example": "지금 학교에 가요.", "exampleTrans": "現在去學校。", "diff": "easy" },
  { "word": "집", "pos": "n.", "trans": "家", "example": "빨리 집에 가고 싶어요.", "exampleTrans": "想快點回家。", "diff": "easy" },
  { "word": "선생님", "pos": "n.", "trans": "老師", "example": "선생님, 질문이 있어요.", "exampleTrans": "老師，我有個問題。", "diff": "easy" },
  { "word": "친구", "pos": "n.", "trans": "朋友", "example": "어제 친구를 만났어요.", "exampleTrans": "昨天見了朋友。", "diff": "easy" },
  { "word": "책", "pos": "n.", "trans": "書", "example": "도서관에서 책을 읽고 있어요.", "exampleTrans": "正在圖書館讀書。", "diff": "easy" },
  { "word": "사과", "pos": "n.", "trans": "蘋果", "example": "사과가 아주 달아요.", "exampleTrans": "蘋果非常甜。", "diff": "easy" },
  { "word": "정말", "pos": "adv.", "trans": "真的", "example": "이 음식 정말 맛있네요!", "exampleTrans": "這食物真的很好吃呢！", "diff": "easy" },
  { "word": "오늘", "pos": "n.", "trans": "今天", "example": "오늘은 날씨가 좋네요.", "exampleTrans": "今天天氣很好呢。", "diff": "easy" },
  { "word": "내일", "pos": "n.", "trans": "明天", "example": "내일 만나요.", "exampleTrans": "明天見。", "diff": "easy" },
  { "word": "어제", "pos": "n.", "trans": "昨天", "example": "어제는 바빴어요.", "exampleTrans": "昨天很忙。", "diff": "easy" },
  { "word": "지금", "pos": "n.", "trans": "現在", "example": "지금 뭐 해요?", "exampleTrans": "現在在做什麼？", "diff": "easy" },
  { "word": "여기", "pos": "n.", "trans": "這裡", "example": "여기에 앉으세요.", "exampleTrans": "請坐在這裡。", "diff": "easy" },
  { "word": "무엇", "pos": "pron.", "trans": "什麼", "example": "무엇을 도와드릴까요?", "exampleTrans": "有什麼可以幫您的？", "diff": "easy" },
  { "word": "누구", "pos": "pron.", "trans": "誰", "example": "누구세요?", "exampleTrans": "請問是誰？", "diff": "easy" },
  { "word": "언제", "pos": "adv.", "trans": "什麼時候", "example": "언제 한국에 와요?", "exampleTrans": "什麼時候來韓國？", "diff": "easy" },
  { "word": "어디", "pos": "adv.", "trans": "哪裡", "example": "어디에 사세요?", "exampleTrans": "您住在哪裡？", "diff": "easy" },
  { "word": "왜", "pos": "adv.", "trans": "為什麼", "example": "왜 늦었어요?", "exampleTrans": "為什麼遲到了？", "diff": "easy" },
  { "word": "감사합니다", "pos": "phrase", "trans": "謝謝 (敬語)", "example": "도와주셔서 감사합니다.", "exampleTrans": "謝謝您的幫助。", "diff": "easy" },
  { "word": "죄송합니다", "pos": "phrase", "trans": "對不起 (敬語)", "example": "늦어서 죄송합니다.", "exampleTrans": "對不起，我遲到了。", "diff": "easy" },
  { "word": "안녕", "pos": "phrase", "trans": "你好 / 再見 (非敬語)", "example": "안녕! 오랜만이야.", "exampleTrans": "你好！好久不見。", "diff": "easy" },
  { "word": "나무", "pos": "n.", "trans": "樹", "example": "공원에 나무가 많아요.", "exampleTrans": "公園裡樹很多。", "diff": "easy" },
  { "word": "바다", "pos": "n.", "trans": "大海", "example": "여름에 바다에 가요.", "exampleTrans": "夏天去大海。", "diff": "easy" },
  { "word": "산", "pos": "n.", "trans": "山", "example": "주말에 산에 올라가요.", "exampleTrans": "週末去爬山。", "diff": "easy" },
  { "word": "강", "pos": "n.", "trans": "河流", "example": "한강은 정말 넓어요.", "exampleTrans": "漢江真的很寬。", "diff": "easy" },
  { "word": "하늘", "pos": "n.", "trans": "天空", "example": "하늘이 참 맑아요.", "exampleTrans": "天空真晴朗。", "diff": "easy" },
  { "word": "구름", "pos": "n.", "trans": "雲", "example": "하늘에 구름이 떠 있어요.", "exampleTrans": "天空飄著雲。", "diff": "easy" },
  { "word": "비", "pos": "n.", "trans": "雨", "example": "비가 오고 있어요.", "exampleTrans": "正在下雨。", "diff": "easy" },
  { "word": "눈", "pos": "n.", "trans": "雪 / 眼睛", "example": "겨울에 눈이 와요.", "exampleTrans": "冬天會下雪。", "diff": "easy" },
  { "word": "해", "pos": "n.", "trans": "太陽", "example": "해가 떴어요.", "exampleTrans": "太陽升起來了。", "diff": "easy" },
  { "word": "달", "pos": "n.", "trans": "月亮", "example": "밤하늘에 달이 밝아요.", "exampleTrans": "夜空中的月亮很亮。", "diff": "easy" },
  { "word": "별", "pos": "n.", "trans": "星星", "example": "별이 반짝거려요.", "exampleTrans": "星星在閃爍。", "diff": "easy" },
  { "word": "꽃", "pos": "n.", "trans": "花", "example": "꽃이 활짝 피었어요.", "exampleTrans": "花兒盛開了。", "diff": "easy" },
  { "word": "바람", "pos": "n.", "trans": "風", "example": "시원한 바람이 불어요.", "exampleTrans": "吹著涼爽的風。", "diff": "easy" },

  // --- Medium: Daily Life, Verbs, Adjectives, Places ---
  { "word": "가다", "pos": "v.", "trans": "去", "verbForms": "가요 / 갔어요", "example": "어디에 가고 싶어요?", "exampleTrans": "想去哪裡？", "diff": "medium" },
  { "word": "오다", "pos": "v.", "trans": "來", "verbForms": "와요 / 왔어요", "example": "여기에 언제 왔어요?", "exampleTrans": "什麼時候來這裡的？", "diff": "medium" },
  { "word": "먹다", "pos": "v.", "trans": "吃", "verbForms": "먹어요 / 먹었어요", "example": "저녁을 많이 먹었어요.", "exampleTrans": "晚餐吃了很多。", "diff": "medium" },
  { "word": "마시다", "pos": "v.", "trans": "喝", "verbForms": "마셔요 / 마셨어요", "example": "주스를 시원하게 마셔요.", "exampleTrans": "痛快地喝果汁。", "diff": "medium" },
  { "word": "보다", "pos": "v.", "trans": "看", "verbForms": "봐요 / 봤어요", "example": "어제 영화를 봤어요.", "exampleTrans": "昨天看了電影。", "diff": "medium" },
  { "word": "듣다", "pos": "v.", "trans": "聽", "verbForms": "들어요 / 들었어요", "example": "음악을 듣는 것을 좋아해요.", "exampleTrans": "喜歡聽音樂。", "diff": "medium" },
  { "word": "읽다", "pos": "v.", "trans": "讀", "verbForms": "읽어요 / 읽었어요", "example": "매일 신문을 읽어요.", "exampleTrans": "每天讀報紙。", "diff": "medium" },
  { "word": "쓰다", "pos": "v.", "trans": "寫 / 使用", "verbForms": "써요 / 썼어요", "example": "편지를 써요.", "exampleTrans": "寫信。", "diff": "medium" },
  { "word": "말하다", "pos": "v.", "trans": "說", "verbForms": "말해요 / 말했어요", "example": "다시 한번 말해 주세요.", "exampleTrans": "請再說一次。", "diff": "medium" },
  { "word": "공부하다", "pos": "v.", "trans": "學習", "verbForms": "공부해요 / 공부했어요", "example": "한국어를 열심히 공부해요.", "exampleTrans": "努力學習韓文。", "diff": "medium" },
  { "word": "일하다", "pos": "v.", "trans": "工作", "verbForms": "일해요 / 일했어요", "example": "밤늦게까지 일했어요.", "exampleTrans": "工作到深夜。", "diff": "medium" },
  { "word": "운동하다", "pos": "v.", "trans": "運動", "verbForms": "운동해요 / 운동했어요", "example": "공원에서 운동해요.", "exampleTrans": "在公園運動。", "diff": "medium" },
  { "word": "자다", "pos": "v.", "trans": "睡覺", "verbForms": "자요 / 잤어요", "example": "일찍 자고 일찍 일어나요.", "exampleTrans": "早睡早起。", "diff": "medium" },
  { "word": "만나다", "pos": "v.", "trans": "見面", "verbForms": "만나요 / 만났어요", "example": "내일 친구를 만날 거예요.", "exampleTrans": "明天要見朋友。", "diff": "medium" },
  { "word": "사다", "pos": "v.", "trans": "買", "verbForms": "사요 / 샀어요", "example": "백화점에서 선물을 샀어요.", "exampleTrans": "在百貨公司買了禮物。", "diff": "medium" },
  { "word": "팔다", "pos": "v.", "trans": "賣", "verbForms": "팔아요 / 팔았어요", "example": "시장에서 과일을 팔아요.", "exampleTrans": "在市場賣水果。", "diff": "medium" },
  { "word": "알다", "pos": "v.", "trans": "知道", "verbForms": "알아요 / 알았어요", "example": "그 사람을 잘 알아요.", "exampleTrans": "我很了解那個人。", "diff": "medium" },
  { "word": "모르다", "pos": "v.", "trans": "不知道", "verbForms": "몰라요 / 몰랐어요", "example": "그 소식은 몰랐어요.", "exampleTrans": "不知道那個消息。", "diff": "medium" },
  { "word": "입다", "pos": "v.", "trans": "穿 (衣)", "verbForms": "입어요 / 입었어요", "example": "코트를 입으세요.", "exampleTrans": "請穿上大衣。", "diff": "medium" },
  { "word": "벗다", "pos": "v.", "trans": "脫 (衣)", "verbForms": "벗어요 / 벗었어요", "example": "신발을 벗고 들어오세요.", "exampleTrans": "請脫鞋進來。", "diff": "medium" },
  { "word": "전화하다", "pos": "v.", "trans": "打電話", "verbForms": "전화해요 / 전화했어요", "example": "집에 가서 전화할게요.", "exampleTrans": "我回家後打電話。", "diff": "medium" },
  { "word": "청소하다", "pos": "v.", "trans": "打掃", "verbForms": "청소해요 / 청소했어요", "example": "주말에 방을 청소해요.", "exampleTrans": "週末打掃房間。", "diff": "medium" },
  { "word": "요리하다", "pos": "v.", "trans": "做飯", "verbForms": "요리해요 / 요리했어요", "example": "오늘 저녁은 제가 요리할게요.", "exampleTrans": "今天晚餐由我來做。", "diff": "medium" },
  { "word": "샤워하다", "pos": "v.", "trans": "洗澡", "verbForms": "샤워해요 / 샤워했어요", "example": "아침마다 샤워를 해요.", "exampleTrans": "每天早上都洗澡。", "diff": "medium" },
  { "word": "산책하다", "pos": "v.", "trans": "散步", "verbForms": "산책해요 / 산책했어요", "example": "강아지와 함께 산책해요.", "exampleTrans": "和狗狗一起散步。", "diff": "medium" },
  { "word": "쇼핑하다", "pos": "v.", "trans": "購物", "verbForms": "쇼핑해요 / 쇼핑했어요", "example": "주말에 친구랑 쇼핑해요.", "exampleTrans": "週末和朋友去購物。", "diff": "medium" },
  { "word": "노래하다", "pos": "v.", "trans": "唱歌", "verbForms": "노래해요 / 노래했어요", "example": "노래방에서 노래해요.", "exampleTrans": "在 KTV 唱歌。", "diff": "medium" },
  { "word": "춤추다", "pos": "v.", "trans": "跳舞", "verbForms": "춤춰요 / 춤췄어요", "example": "클럽에서 춤을 춰요.", "exampleTrans": "在夜店跳舞。", "diff": "medium" },
  { "word": "운전하다", "pos": "v.", "trans": "開車", "verbForms": "운전해요 / 운전했어요", "example": "아버지가 차를 운전하세요.", "exampleTrans": "爸爸在開車。", "diff": "medium" },
  { "word": "여행하다", "pos": "v.", "trans": "旅行", "verbForms": "여행해요 / 여행했어요", "example": "제주도를 여행하고 싶어요.", "exampleTrans": "想去濟州島旅行。", "diff": "medium" },
  { "word": "예쁘다", "pos": "adj.", "trans": "漂亮", "example": "바다가 정말 예뻐요.", "exampleTrans": "大海真的很漂亮。", "diff": "medium" },
  { "word": "멋있다", "pos": "adj.", "trans": "帥氣", "example": "그 가수는 정말 멋있어요.", "exampleTrans": "那個歌手真的很帥。", "diff": "medium" },
  { "word": "맛있다", "pos": "adj.", "trans": "好吃", "example": "비빔밥이 정말 맛있어요.", "exampleTrans": "拌飯真的很好吃。", "diff": "medium" },
  { "word": "비싸다", "pos": "adj.", "trans": "貴", "example": "이 가방은 너무 비싸요.", "exampleTrans": "這個包包太貴了。", "diff": "medium" },
  { "word": "싸다", "pos": "adj.", "trans": "便宜", "example": "여기는 물건이 싸요.", "exampleTrans": "這裡的東西很便宜。", "diff": "medium" },
  { "word": "크다", "pos": "adj.", "trans": "大", "example": "집이 아주 커요.", "exampleTrans": "家很大。", "diff": "medium" },
  { "word": "작다", "pos": "adj.", "trans": "小", "example": "방이 조금 작아요.", "exampleTrans": "房間有點小。", "diff": "medium" },
  { "word": "길다", "pos": "adj.", "trans": "長", "example": "머리가 아주 길어요.", "exampleTrans": "頭髮很長。", "diff": "medium" },
  { "word": "짧다", "pos": "adj.", "trans": "短", "example": "치마가 너무 짧아요.", "exampleTrans": "裙子太短了。", "diff": "medium" },
  { "word": "빠르다", "pos": "adj.", "trans": "快", "example": "지하철이 정말 빨라요.", "exampleTrans": "地鐵真的很快。", "diff": "medium" },
  { "word": "느리다", "pos": "adj.", "trans": "慢", "example": "컴퓨터가 너무 느려요.", "exampleTrans": "電腦太慢了。", "diff": "medium" },
  { "word": "멀다", "pos": "adj.", "trans": "遠", "example": "회사가 너무 멀어요.", "exampleTrans": "公司太遠了。", "diff": "medium" },
  { "word": "가깝다", "pos": "adj.", "trans": "近", "example": "역이 집에서 가까워요.", "exampleTrans": "車站離家很近。", "diff": "medium" },
  { "word": "쉽다", "pos": "adj.", "trans": "容易", "example": "시험이 아주 쉬웠어요.", "exampleTrans": "考試非常容易。", "diff": "medium" },
  { "word": "어렵다", "pos": "adj.", "trans": "難", "example": "한국어가 조금 어려워요.", "exampleTrans": "韓文有點難。", "diff": "medium" },
  { "word": "덥다", "pos": "adj.", "trans": "熱", "example": "여름은 너무 더워요.", "exampleTrans": "夏天太熱了。", "diff": "medium" },
  { "word": "춥다", "pos": "adj.", "trans": "冷", "example": "겨울은 너무 추워요.", "exampleTrans": "冬天太冷了。", "diff": "medium" },
  { "word": "따뜻하다", "pos": "adj.", "trans": "溫暖", "example": "봄은 날씨가 따뜻해요.", "exampleTrans": "春天的新氣溫暖。", "diff": "medium" },
  { "word": "시원하다", "pos": "adj.", "trans": "涼爽", "example": "가을은 바람이 시원해요.", "exampleTrans": "秋天的風很涼爽。", "diff": "medium" },
  { "word": "가볍다", "pos": "adj.", "trans": "輕", "example": "가방이 아주 가벼워요.", "exampleTrans": "包包非常輕。", "diff": "medium" },
  { "word": "무겁다", "pos": "adj.", "trans": "重", "example": "짐이 너무 무거워요.", "exampleTrans": "行李太重了。", "diff": "medium" },
  { "word": "지하철", "pos": "n.", "trans": "地鐵", "example": "지하철을 타고 가요.", "exampleTrans": "搭地鐵去。", "diff": "medium" },
  { "word": "버스", "pos": "n.", "trans": "公車", "example": "버스 정류장이 어디예요?", "exampleTrans": "公車站在哪裡？", "diff": "medium" },
  { "word": "택시", "pos": "n.", "trans": "計程車", "example": "택시를 잡아요.", "exampleTrans": "攔計程車。", "diff": "medium" },
  { "word": "비행기", "pos": "n.", "trans": "飛機", "example": "비행기를 타고 해외로 가요.", "exampleTrans": "搭飛機出國。", "diff": "medium" },
  { "word": "공항", "pos": "n.", "trans": "機場", "example": "인천공항은 정말 커요.", "exampleTrans": "仁川機場真的很大。", "diff": "medium" },
  { "word": "기차", "pos": "n.", "trans": "火車", "example": "부산행 기차를 타요.", "exampleTrans": "搭乘開往釜山的火車。", "diff": "medium" },
  { "word": "자전거", "pos": "n.", "trans": "腳踏車", "example": "한강에서 자전거를 타요.", "exampleTrans": "在漢江騎腳踏車。", "diff": "medium" },
  { "word": "병원", "pos": "n.", "trans": "醫院", "example": "몸이 아파서 병원에 가요.", "exampleTrans": "因為身體不舒服去醫院。", "diff": "medium" },
  { "word": "약국", "pos": "n.", "trans": "藥局", "example": "약국에서 감기약을 사요.", "exampleTrans": "在藥局買感冒藥。", "diff": "medium" },
  { "word": "은행", "pos": "n.", "trans": "銀行", "example": "은행에서 돈을 찾아요.", "exampleTrans": "在銀行領錢。", "diff": "medium" },
  { "word": "우체국", "pos": "n.", "trans": "郵局", "example": "우체국에서 편지를 보내요.", "exampleTrans": "在郵局寄信。", "diff": "medium" },
  { "word": "편의점", "pos": "n.", "trans": "便利商店", "example": "편의점에서 라면을 사요.", "exampleTrans": "在便利商店買拉麵。", "diff": "medium" },
  { "word": "백화점", "pos": "n.", "trans": "百貨公司", "example": "백화점에서 쇼핑을 해요.", "exampleTrans": "在百貨公司購物。", "diff": "medium" },
  { "word": "영화관", "pos": "n.", "trans": "電影院", "example": "영화관에서 팝콘을 먹어요.", "exampleTrans": "在電影院吃爆米花。", "diff": "medium" },
  { "word": "카페", "pos": "n.", "trans": "咖啡廳", "example": "카페에서 친구를 기다려요.", "exampleTrans": "在咖啡廳等朋友。", "diff": "medium" },
  { "word": "식당", "pos": "n.", "trans": "餐廳", "example": "맛집 식당에 줄을 서요.", "exampleTrans": "在知名餐廳排隊。", "diff": "medium" },
  { "word": "도서관", "pos": "n.", "trans": "圖書館", "example": "도서관은 조용히 해야 해요.", "exampleTrans": "圖書館要保持安靜。", "diff": "medium" },
  { "word": "공원", "pos": "n.", "trans": "公園", "example": "공원에서 조깅을 해요.", "exampleTrans": "在公園慢跑。", "diff": "medium" },
  { "word": "바다", "pos": "n.", "trans": "大海", "example": "여름 휴가로 바다에 가요.", "exampleTrans": "夏天休假去大海。", "diff": "medium" },
  { "word": "시장", "pos": "n.", "trans": "市場", "example": "전통 시장에서 떡볶이를 먹어요.", "exampleTrans": "在傳統市場吃辣炒年糕。", "diff": "medium" },
  { "word": "봄", "pos": "n.", "trans": "春天", "example": "봄에는 벚꽃이 피어요.", "exampleTrans": "春天櫻花盛開。", "diff": "medium" },
  { "word": "여름", "pos": "n.", "trans": "夏天", "example": "여름에는 수박을 먹어요.", "exampleTrans": "夏天吃西瓜。", "diff": "medium" },
  { "word": "가을", "pos": "n.", "trans": "秋天", "example": "가을은 독서의 계절이에요.", "exampleTrans": "秋天是讀書的季節。", "diff": "medium" },
  { "word": "겨울", "pos": "n.", "trans": "冬天", "example": "겨울에는 붕어빵이 맛있어요.", "exampleTrans": "冬天的紅豆餅很好吃。", "diff": "medium" },
  { "word": "월요일", "pos": "n.", "trans": "星期一", "example": "월요일은 항상 피곤해요.", "exampleTrans": "星期一總是很累。", "diff": "medium" },
  { "word": "화요일", "pos": "n.", "trans": "星期二", "example": "화요일에 회의가 있어요.", "exampleTrans": "星期二有會議。", "diff": "medium" },
  { "word": "수요일", "pos": "n.", "trans": "星期三", "example": "수요일은 일주일의 중간이에요.", "exampleTrans": "星期三是一週的中間。", "diff": "medium" },
  { "word": "목요일", "pos": "n.", "trans": "星期四", "example": "목요일 밤에 야식을 먹어요.", "exampleTrans": "星期四晚上吃宵夜。", "diff": "medium" },
  { "word": "금요일", "pos": "n.", "trans": "星期五", "example": "금요일은 불금이에요!", "exampleTrans": "星期五是燃燒的星期五！", "diff": "medium" },
  { "word": "토요일", "pos": "n.", "trans": "星期六", "example": "토요일에 늦잠을 자요.", "exampleTrans": "星期六睡懶覺。", "diff": "medium" },
  { "word": "일요일", "pos": "n.", "trans": "星期日", "example": "일요일은 집에서 쉬어요.", "exampleTrans": "星期日在家休息。", "diff": "medium" },
  { "word": "머리", "pos": "n.", "trans": "頭 / 頭髮", "example": "머리가 아파서 쉬어야겠어요.", "exampleTrans": "頭很痛，得休息一下。", "diff": "medium" },
  { "word": "눈", "pos": "n.", "trans": "眼睛", "example": "눈이 나빠서 안경을 써요.", "exampleTrans": "視力不好所以戴眼鏡。", "diff": "medium" },
  { "word": "코", "pos": "n.", "trans": "鼻子", "example": "코가 높아서 부러워요.", "exampleTrans": "鼻子很高，真令人羨慕。", "diff": "medium" },
  { "word": "입", "pos": "n.", "trans": "嘴巴", "example": "입을 크게 벌리세요.", "exampleTrans": "請把嘴張大。", "diff": "medium" },
  { "word": "귀", "pos": "n.", "trans": "耳朵", "example": "귀가 아파서 병원에 갔어요.", "exampleTrans": "耳朵痛所以去了醫院。", "diff": "medium" },
  { "word": "손", "pos": "n.", "trans": "手", "example": "손을 깨끗이 씻으세요.", "exampleTrans": "請把手洗乾淨。", "diff": "medium" },
  { "word": "발", "pos": "n.", "trans": "腳", "example": "발이 커서 신발 사기 힘들어요.", "exampleTrans": "腳太大，買鞋很辛苦。", "diff": "medium" },
  { "word": "팔", "pos": "n.", "trans": "手臂 / 八", "example": "팔을 다쳐서 깁스를 했어요.", "exampleTrans": "手臂受傷了所以打了石膏。", "diff": "medium" },
  { "word": "다리", "pos": "n.", "trans": "腿 / 橋", "example": "다리가 길어서 옷태가 나요.", "exampleTrans": "腿很長，穿衣服很好看。", "diff": "medium" },
  { "word": "어깨", "pos": "n.", "trans": "肩膀", "example": "어깨가 결려서 마사지를 받아요.", "exampleTrans": "肩膀痠痛所以去按摩。", "diff": "medium" },
  { "word": "배", "pos": "n.", "trans": "肚子 / 梨子 / 船", "example": "배가 고파서 라면을 끓여요.", "exampleTrans": "肚子餓所以煮了泡麵。", "diff": "medium" },
  { "word": "등", "pos": "n.", "trans": "背部", "example": "등이 가려워서 긁었어요.", "exampleTrans": "背很癢所以抓了一下。", "diff": "medium" },
  { "word": "목", "pos": "n.", "trans": "脖子 / 喉嚨", "example": "목이 쉬어서 말을 못 해요.", "exampleTrans": "喉嚨啞了所以不能說話。", "diff": "medium" },
  { "word": "얼굴", "pos": "n.", "trans": "臉", "example": "얼굴에 화장을 해요.", "exampleTrans": "在臉上化妝。", "diff": "medium" },
  { "word": "피부", "pos": "n.", "trans": "皮膚", "example": "피부가 좋아서 동안이에요.", "exampleTrans": "皮膚很好所以看起來很年輕。", "diff": "medium" },

  // --- Hard: Emotions, Actions, Abstract, Social, Advanced Daily ---
  { "word": "기쁘다", "pos": "adj.", "trans": "高興", "example": "합격 소식을 듣고 정말 기뻤어요.", "exampleTrans": "聽到錄取的消息真的很開心。", "diff": "hard" },
  { "word": "슬프다", "pos": "adj.", "trans": "悲傷", "example": "슬픈 영화를 보고 울었어요.", "exampleTrans": "看了悲傷的電影哭了。", "diff": "hard" },
  { "word": "화나다", "pos": "v.", "trans": "生氣", "example": "약속을 안 지켜서 화가 났어요.", "exampleTrans": "因為不守約定所以生氣了。", "diff": "hard" },
  { "word": "행복하다", "pos": "adj.", "trans": "幸福", "example": "사랑하는 사람과 함께라 행복해요.", "exampleTrans": "和心愛的人在一起很幸福。", "diff": "hard" },
  { "word": "우울하다", "pos": "adj.", "trans": "憂鬱", "example": "비가 오면 마음이 우울해져요.", "exampleTrans": "一下雨心情就變得憂鬱。", "diff": "hard" },
  { "word": "부끄럽다", "pos": "adj.", "trans": "羞愧 / 害羞", "example": "실수를 해서 너무 부끄러웠어요.", "exampleTrans": "因為犯了錯覺得很羞愧。", "diff": "hard" },
  { "word": "긴장되다", "pos": "v.", "trans": "緊張", "example": "면접을 앞두고 긴장돼요.", "exampleTrans": "面試前覺得很緊張。", "diff": "hard" },
  { "word": "신나다", "pos": "v.", "trans": "興奮 / 開心", "example": "콘서트에 가니까 정말 신나요.", "exampleTrans": "去演唱會真的很興奮。", "diff": "hard" },
  { "word": "답답하다", "pos": "adj.", "trans": "鬱悶 / 悶熱", "example": "방이 좁아서 공기가 답답해요.", "exampleTrans": "房間很小，空氣很悶。", "diff": "hard" },
  { "word": "심심하다", "pos": "adj.", "trans": "無聊 (沒事做)", "example": "집에 혼자 있으면 심심해요.", "exampleTrans": "一個人在家很無聊。", "diff": "hard" },
  { "word": "귀찮다", "pos": "adj.", "trans": "麻煩 / 懶得", "example": "청소하기가 너무 귀찮아요.", "exampleTrans": "懶得打掃環境。", "diff": "hard" },
  { "word": "부럽다", "pos": "adj.", "trans": "羨慕", "example": "친구가 여행 가는 게 부러워요.", "exampleTrans": "羨慕朋友去旅行。", "diff": "hard" },
  { "word": "걱정하다", "pos": "v.", "trans": "擔心", "example": "부모님께 걱정을 끼쳐 드렸어요.", "exampleTrans": "讓父母擔心了。", "diff": "hard" },
  { "word": "생각하다", "pos": "v.", "trans": "想 / 思考", "example": "미래에 대해 깊이 생각해요.", "exampleTrans": "深入思考關於未來的規劃。", "diff": "hard" },
  { "word": "기억하다", "pos": "v.", "trans": "記得", "example": "우리의 약속을 꼭 기억해 주세요.", "exampleTrans": "請務必記得我們的約定。", "diff": "hard" },
  { "word": "이해하다", "pos": "v.", "trans": "理解", "example": "그의 행동을 도저히 이해 못 하겠어요.", "exampleTrans": "完全無法理解他的行為。", "diff": "hard" },
  { "word": "준비하다", "pos": "v.", "trans": "準備", "example": "시험 준비를 철저히 해야 해요.", "exampleTrans": "得徹底準備考試。", "diff": "hard" },
  { "word": "결정하다", "pos": "v.", "trans": "決定", "example": "오랫동안 고민해서 결정했어요.", "exampleTrans": "煩惱很久後決定了。", "diff": "hard" },
  { "word": "포기하다", "pos": "v.", "trans": "放棄", "example": "절대로 꿈을 포기하지 마세요.", "exampleTrans": "絕對不要放棄夢想。", "diff": "hard" },
  { "word": "노력하다", "pos": "v.", "trans": "努力", "example": "성공하기 위해 매일 노력해요.", "exampleTrans": "為了成功每天都在努力。", "diff": "hard" },
  { "word": "시작하다", "pos": "v.", "trans": "開始", "example": "새로운 일을 시작하기에 좋은 날이에요.", "exampleTrans": "是個適合開始新工作的好日子。", "diff": "hard" },
  { "word": "끝내다", "pos": "v.", "trans": "結束", "example": "오늘 할 일을 다 끝냈어요.", "exampleTrans": "今天的工作都做完了。", "diff": "hard" },
  { "word": "성공하다", "pos": "v.", "trans": "成功", "example": "마침내 다이어트에 성공했어요.", "exampleTrans": "終於減肥成功了。", "diff": "hard" },
  { "word": "실패하다", "pos": "v.", "trans": "失敗", "example": "실패는 성공의 어머니예요.", "exampleTrans": "失敗是成功之母。", "diff": "hard" },
  { "word": "변하다", "pos": "v.", "trans": "改變", "example": "10년 사이에 동네가 많이 변했네요.", "exampleTrans": "這十年來社區改變了很多呢。", "diff": "hard" },
  { "word": "찾다", "pos": "v.", "trans": "尋找 / 領取", "example": "잃어버린 지갑을 찾았어요.", "exampleTrans": "找到了弄丟的錢包。", "diff": "hard" },
  { "word": "잃어버리다", "pos": "v.", "trans": "弄丟", "example": "핸드폰을 어디서 잃어버렸는지 몰라요.", "exampleTrans": "不知道在哪裡弄丟了手機。", "diff": "hard" },
  { "word": "도착하다", "pos": "v.", "trans": "抵達", "example": "역에 도착하면 연락할게요.", "exampleTrans": "抵達車站後會聯絡你。", "diff": "hard" },
  { "word": "출발하다", "pos": "v.", "trans": "出發", "example": "정시에 버스가 출발해요.", "exampleTrans": "巴士準時出發。", "diff": "hard" },
  { "word": "기다리다", "pos": "v.", "trans": "等待", "example": "카페에서 1시간 동안 기다렸어요.", "exampleTrans": "在咖啡廳等了一小時。", "diff": "hard" },
  { "word": "약속하다", "pos": "v.", "trans": "約定", "example": "다시는 늦지 않겠다고 약속했어요.", "exampleTrans": "約定好再也不遲到了。", "diff": "hard" },
  { "word": "도와주다", "pos": "v.", "trans": "幫忙", "example": "어려운 이웃을 도와주세요.", "exampleTrans": "請幫助困難的鄰居。", "diff": "hard" },
  { "word": "빌리다", "pos": "v.", "trans": "借", "example": "도서관에서 책을 빌렸어요.", "exampleTrans": "在圖書館借了書。", "diff": "hard" },
  { "word": "돌려주다", "pos": "v.", "trans": "還給", "example": "빌린 돈을 빨리 돌려주세요.", "exampleTrans": "請快點還我借的錢。", "diff": "hard" },
  { "word": "가르치다", "pos": "v.", "trans": "教", "example": "외국인에게 한국어를 가르쳐요.", "exampleTrans": "教外國人韓文。", "diff": "hard" },
  { "word": "배우다", "pos": "v.", "trans": "學習", "example": "수영을 배우기 시작했어요.", "exampleTrans": "開始學習游泳了。", "diff": "hard" },
  { "word": "사용하다", "pos": "v.", "trans": "使用", "example": "신용카드를 자주 사용해요.", "exampleTrans": "經常使用信用卡。", "diff": "hard" },
  { "word": "준비물", "pos": "n.", "trans": "準備物品", "example": "내일 수업 준비물을 챙겨요.", "exampleTrans": "收拾好明天課堂的準備物品。", "diff": "hard" },
  { "word": "숙제", "pos": "n.", "trans": "作業", "example": "숙제가 너무 많아서 잠을 못 잤어요.", "exampleTrans": "作業太多所以沒睡覺。", "diff": "hard" },
  { "word": "회의", "pos": "n.", "trans": "會議", "example": "긴급 회의가 소집되었어요.", "exampleTrans": "召集了緊急會議。", "diff": "hard" },
  { "word": "보고서", "pos": "n.", "trans": "報告書", "example": "내일까지 보고서를 제출하세요.", "exampleTrans": "請在明天前提交報告書。", "diff": "hard" },
  { "word": "월급", "pos": "n.", "trans": "月薪", "example": "월급날만 기다리고 있어요.", "exampleTrans": "只等著發薪日。", "diff": "hard" },
  { "word": "휴가", "pos": "n.", "trans": "休假", "example": "이번 휴가에는 해외여행을 가요.", "exampleTrans": "這次休假要去海外旅行。", "diff": "hard" },
  { "word": "출장", "pos": "n.", "trans": "出差", "example": "사장님이 일본으로 출장을 가셨어요.", "exampleTrans": "老闆去日本出差了。", "diff": "hard" },
  { "word": "면접", "pos": "n.", "trans": "面試", "example": "내일은 중요한 입사 면접이 있어요.", "exampleTrans": "明天有個重要的入職面試。", "diff": "hard" },
  { "word": "승진", "pos": "n.", "trans": "升遷", "example": "과장으로 승진해서 축하 파티를 했어요.", "exampleTrans": "升職為課長所以舉辦了慶祝派對。", "diff": "hard" },
  { "word": "야근", "pos": "n.", "trans": "加班", "example": "일이 밀려서 오늘 야근해야 해요.", "exampleTrans": "事情堆積如山，今天得加班。", "diff": "hard" },
  { "word": "회식", "pos": "n.", "trans": "聚餐", "example": "오늘 밤에 팀 회식이 있어요.", "exampleTrans": "今天晚上有部門聚餐。", "diff": "hard" },
  { "word": "퇴근", "pos": "n.", "trans": "下班", "example": "6시 정각에 퇴근하는 게 꿈이에요.", "exampleTrans": "準時 6 點下班是我的夢想。", "diff": "hard" },
  { "word": "결혼", "pos": "n.", "trans": "結婚", "example": "두 사람은 내년에 결혼할 예정이에요.", "exampleTrans": "兩個人預定明年結婚。", "diff": "hard" },
  { "word": "이혼", "pos": "n.", "trans": "離婚", "example": "그들은 성격 차이로 이혼했어요.", "exampleTrans": "他們因為性格不合而離婚了。", "diff": "hard" },
  { "word": "연애", "pos": "n.", "trans": "戀愛", "example": "연애를 시작한 지 한 달 됐어요.", "exampleTrans": "開始戀愛一個月了。", "diff": "hard" },
  { "word": "소개팅", "pos": "n.", "trans": "相親 / 介紹認識", "example": "이번 주말에 소개팅이 잡혔어요.", "exampleTrans": "這週末安排了相親。", "diff": "hard" },
  { "word": "성격", "pos": "n.", "trans": "性格", "example": "성격이 밝아서 친구가 많아요.", "exampleTrans": "性格開朗所以朋友很多。", "diff": "hard" },
  { "word": "취미", "pos": "n.", "trans": "興趣", "example": "제 취미는 영화 감상이에요.", "exampleTrans": "我的興趣是看電影。", "diff": "hard" },
  { "word": "습관", "pos": "n.", "trans": "習慣", "example": "좋은 습관을 들이는 게 중요해요.", "exampleTrans": "養成好習慣是很重要的。", "diff": "hard" },
  { "word": "추억", "pos": "n.", "trans": "回憶", "example": "어린 시절의 추억이 생생해요.", "exampleTrans": "童年的回憶歷歷在目。", "diff": "hard" },
  { "word": "비밀", "pos": "n.", "trans": "秘密", "example": "이건 우리 둘만의 비밀이에요.", "exampleTrans": "這是我們兩個人之間的秘密。", "diff": "hard" },
  { "word": "거짓말", "pos": "n.", "trans": "謊言", "example": "거짓말은 신뢰를 깨뜨려요.", "exampleTrans": "謊言會破壞信任。", "diff": "hard" },
  { "word": "진실", "pos": "n.", "trans": "真相", "example": "언젠가는 진실이 밝혀질 거예요.", "exampleTrans": "真相總有一天會水落石出。", "diff": "hard" },
  { "word": "고민", "pos": "n.", "trans": "煩惱", "example": "요즘 진로 때문에 고민이 많아요.", "exampleTrans": "最近因為前途問題有很多煩惱。", "diff": "hard" },
  { "word": "스트레스", "pos": "n.", "trans": "壓力", "example": "스트레스를 풀기 위해 운동해요.", "exampleTrans": "為了減壓而運動。", "diff": "hard" },

  // --- Pro: Social Issues, Tech, Advanced Nuances, Formal Terms ---
  { "word": "환경보호", "pos": "n.", "trans": "環境保護", "example": "환경보호를 위해 플라스틱 사용을 줄여요.", "exampleTrans": "為了環保而減少塑膠的使用。", "diff": "pro" },
  { "word": "지구온난화", "pos": "n.", "trans": "地球暖化", "example": "지구온난화로 인해 북극의 얼음이 녹고 있어요.", "exampleTrans": "因為全球暖化，北極的冰正在融化。", "diff": "pro" },
  { "word": "인공지능", "pos": "n.", "trans": "人工智慧", "example": "인공지능 기술이 빠르게 발전하고 있습니다.", "exampleTrans": "人工智慧技術正在快速發展。", "diff": "pro" },
  { "word": "가상현실", "pos": "n.", "trans": "虛擬實境", "example": "가상현실 게임을 체험해 보셨나요?", "exampleTrans": "你體驗過虛擬實境遊戲嗎？", "diff": "pro" },
  { "word": "암호화폐", "pos": "n.", "trans": "加密貨幣", "example": "암호화폐 투자는 리스크가 큽니다.", "exampleTrans": "加密貨幣投資風險很大。", "diff": "pro" },
  { "word": "부동산", "pos": "n.", "trans": "不動產", "example": "요즘 부동산 가격이 너무 올랐어요.", "exampleTrans": "最近房價漲得太厲害了。", "diff": "pro" },
  { "word": "주식투자", "pos": "n.", "trans": "股票投資", "example": "주식투자로 수익을 냈어요.", "exampleTrans": "透過股票投資獲利了。", "diff": "pro" },
  { "word": "저출산", "pos": "n.", "trans": "低生育率", "example": "저출산 문제는 사회의 심각한 위기입니다.", "exampleTrans": "低生育率問題是社會嚴重的危機。", "diff": "pro" },
  { "word": "고령화", "pos": "n.", "trans": "高齡化", "example": "한국은 고령화 사회로 진입했습니다.", "exampleTrans": "韓國已進入高齡化社會。", "diff": "pro" },
  { "word": "사회적거리두기", "pos": "n.", "trans": "社交距離", "example": "감염 예방을 위해 사회적 거리두기를 실천해요.", "exampleTrans": "為了預防感染而實踐社交距離。", "diff": "pro" },
  { "word": "불평등", "pos": "n.", "trans": "不平等", "example": "빈부 불평등을 해소해야 합니다.", "exampleTrans": "必須解決貧富不平等問題。", "diff": "pro" },
  { "word": "민주주의", "pos": "n.", "trans": "民主主義", "example": "민주주의의 핵심은 투표입니다.", "exampleTrans": "民主主義的核心是投票。", "diff": "pro" },
  { "word": "자유무역", "pos": "n.", "trans": "自由貿易", "example": "자유무역 협정이 체결되었습니다.", "exampleTrans": "簽署了自由貿易協定。", "diff": "pro" },
  { "word": "경제성장", "pos": "n.", "trans": "經濟成長", "example": "국가 경제 성장이 둔화되고 있습니다.", "exampleTrans": "國家經濟成長正在放緩。", "diff": "pro" },
  { "word": "혁신", "pos": "n.", "trans": "創新", "example": "기술 혁신이 세상을 바꿉니다.", "exampleTrans": "技術創新改變世界。", "diff": "pro" },
  { "word": "창의성", "pos": "n.", "trans": "創意性", "example": "아이들의 창의성을 키워주어야 해요.", "exampleTrans": "應該培養孩子們的創意。", "diff": "pro" },
  { "word": "경쟁력", "pos": "n.", "trans": "競爭力", "example": "글로벌 경쟁력을 갖추는 것이 필수입니다.", "exampleTrans": "具備全球競爭力是必要的。", "diff": "pro" },
  { "word": "지속가능성", "pos": "n.", "trans": "永續性", "example": "기업의 지속가능한 경영이 중요합니다.", "exampleTrans": "企業的永續經營很重要。", "diff": "pro" },
  { "word": "책임감", "pos": "n.", "trans": "責任感", "example": "리더에게는 강한 책임감이 요구됩니다.", "exampleTrans": "領導者需要強大的責任感。", "diff": "pro" },
  { "word": "자존감", "pos": "n.", "trans": "自尊心", "example": "자존감을 높이는 방법을 연습해 보세요.", "exampleTrans": "請練習提高自尊心的方法。", "diff": "pro" },
  { "word": "의사소통", "pos": "n.", "trans": "溝通 / 意見交換", "example": "원활한 의사소통이 팀워크의 핵심이에요.", "exampleTrans": "順暢的溝通是團隊合作的核心。", "diff": "pro" },
  { "word": "갈등해결", "pos": "n.", "trans": "衝突解決", "example": "갈등 해결을 위해 대화가 필요합니다.", "exampleTrans": "為了解決衝突，對話是必要的。", "diff": "pro" },
  { "word": "다양성", "pos": "n.", "trans": "多樣性", "example": "문화적 다양성을 존중해야 합니다.", "exampleTrans": "應該尊重文化多樣性。", "diff": "pro" },
  { "word": "편견", "pos": "n.", "trans": "偏見", "example": "타인에 대한 편견을 버리세요.", "exampleTrans": "請捨棄對他人的偏見。", "diff": "pro" },
  { "word": "차별", "pos": "n.", "trans": "歧視", "example": "인종 차별은 절대로 용납될 수 없습니다.", "exampleTrans": "種族歧視絕對不能被容忍。", "diff": "pro" },
  { "word": "봉사활동", "pos": "n.", "trans": "志工活動", "example": "주말마다 봉사활동을 하며 보람을 느껴요.", "exampleTrans": "每個週末做志工，覺得很有意義。", "diff": "pro" },
  { "word": "기부", "pos": "n.", "trans": "捐贈", "example": "어려운 아이들을 위해 기부를 결심했어요.", "exampleTrans": "為了困難的孩子們決定捐贈。", "diff": "pro" },
  { "word": "유산", "pos": "n.", "trans": "遺產 / 遺留物", "example": "조상님들의 훌륭한 유산을 물려받았어요.", "exampleTrans": "繼承了祖先優秀的遺產。", "diff": "pro" },
  { "word": "전통", "pos": "n.", "trans": "傳統", "example": "한국의 전통 미를 살린 건축물이에요.", "exampleTrans": "展現韓式傳統美感的建築。", "diff": "pro" },
  { "word": "예술", "pos": "n.", "trans": "藝術", "example": "예술은 우리의 삶을 풍요롭게 합니다.", "exampleTrans": "藝術豐富了我們的生活。", "diff": "pro" },
  { "word": "과학기술", "pos": "n.", "trans": "科學技術", "example": "과학기술의 발달로 수명이 늘어났어요.", "exampleTrans": "隨著科技發展，壽命延長了。", "diff": "pro" },
  { "word": "우주탐사", "pos": "n.", "trans": "太空探索", "example": "우주 탐사는 인류의 거대한 도전입니다.", "exampleTrans": "太空探索是人類巨大的挑戰。", "diff": "pro" },
  { "word": "심리학", "pos": "n.", "trans": "心理學", "example": "사람의 마음을 알기 위해 심리학을 배워요.", "exampleTrans": "為了了解人心而學習心理學。", "diff": "pro" },
  { "word": "철학", "pos": "n.", "trans": "哲學", "example": "삶의 철학이 뚜렷한 사람이 좋아요.", "exampleTrans": "我喜歡人生哲學明確的人。", "diff": "pro" },
  { "word": "성실하다", "pos": "adj.", "trans": "誠實 / 勤奮", "example": "성실하게 일하면 언젠가 인정받을 거예요.", "exampleTrans": "只要誠實工作，總有一天會得到認可。", "diff": "pro" },
  { "word": "겸손하다", "pos": "adj.", "trans": "謙虛", "example": "유명해져도 겸손함을 잃지 마세요.", "exampleTrans": "即便成名也請不要失去謙虛。", "diff": "pro" },
  { "word": "냉정하다", "pos": "adj.", "trans": "冷靜 / 冷酷", "example": "판단할 때는 냉정할 필요가 있습니다.", "exampleTrans": "判斷時有必要保持冷靜。", "diff": "pro" },
  { "word": "솔직하다", "pos": "adj.", "trans": "坦率", "example": "솔직한 감정 표현이 중요해요.", "exampleTrans": "坦率地表達感情很重要。", "diff": "pro" },
  { "word": "신중하다", "pos": "adj.", "trans": "慎重", "example": "중요한 결정이니 신중하게 생각하세요.", "exampleTrans": "因為是重要決定，請慎重思考。", "diff": "pro" },
  { "word": "합리적", "pos": "adj.", "trans": "合理的", "example": "합리적인 소비 습관을 가져야 합니다.", "exampleTrans": "得養成合理的消費習慣。", "diff": "pro" },
  { "word": "효율적", "pos": "adj.", "trans": "有效率的", "example": "시간을 효율적으로 관리하는 게 성공의 비결이에요.", "exampleTrans": "有效管理時間是成功的秘訣。", "diff": "pro" },
  { "word": "적극적", "pos": "adj.", "trans": "積極的", "example": "수업 시간에 적극적으로 참여하세요.", "exampleTrans": "課堂上請積極參與。", "diff": "pro" },
  { "word": "낙천적", "pos": "adj.", "trans": "樂觀的", "example": "낙천적인 성격 덕분에 스트레스를 적게 받아요.", "exampleTrans": "多虧了樂觀的性格，壓力比較小。", "diff": "pro" },
  { "word": "유연하다", "pos": "adj.", "trans": "柔軟 / 靈活", "example": "변화에 유연하게 대처하는 능력이 필요해요.", "exampleTrans": "需要靈活應對變化的能力。", "diff": "pro" },

  // --- NEW BATCH 300-500: Specialized, Nuanced, and More! ---
  { "word": "배달하다", "pos": "v.", "trans": "配送 / 外送", "example": "치킨을 배달시켜 먹었어요.", "exampleTrans": "叫了炸雞外送來吃。", "diff": "medium" },
  { "word": "포장하다", "pos": "v.", "trans": "包裝 / 外帶", "example": "남은 음식을 포장해 주세요.", "exampleTrans": "請幫我打包剩菜。", "diff": "medium" },
  { "word": "주문하다", "pos": "v.", "trans": "訂購 / 點餐", "example": "커피 한 잔 주문할게요.", "exampleTrans": "我要點一杯咖啡。", "diff": "medium" },
  { "word": "결제하다", "pos": "v.", "trans": "結帳 / 付款", "example": "삼성페이로 결제할게요.", "exampleTrans": "我要用三星支付付款。", "diff": "medium" },
  { "word": "환불하다", "pos": "v.", "trans": "退款", "example": "사이즈가 안 맞아서 환불했어요.", "exampleTrans": "因為尺寸不合所以退款了。", "diff": "medium" },
  { "word": "교환하다", "pos": "v.", "trans": "交換 / 換貨", "example": "색상을 다른 걸로 교환해 주세요.", "exampleTrans": "請幫我更換成別的顏色。", "diff": "medium" },
  { "word": "할인하다", "pos": "v.", "trans": "打折", "example": "지금 세일 기간이라 20% 할인해요.", "exampleTrans": "現在是特價期間，打八折。", "diff": "medium" },
  { "word": "적립하다", "pos": "v.", "trans": "累計 / 集點", "example": "포인트를 차곡차곡 적립해요.", "exampleTrans": "一點一點地累積點數。", "diff": "medium" },
  { "word": "품절되다", "pos": "v.", "trans": "售罄", "example": "인기 상품이라 금방 품절됐어요.", "exampleTrans": "因為是人氣商品，很快就賣完了。", "diff": "medium" },
  { "word": "추천하다", "pos": "v.", "trans": "推薦", "example": "이 근처 맛집 좀 추천해 주세요.", "exampleTrans": "請推薦這附近好吃的店。", "diff": "medium" },
  { "word": "검색하다", "pos": "v.", "trans": "搜尋", "example": "모르는 단어는 인터넷에서 검색해요.", "exampleTrans": "不知道的單字就在網路上搜尋。", "diff": "medium" },
  { "word": "공유하다", "pos": "v.", "trans": "分享 / 共享", "example": "좋은 정보는 친구와 공유해요.", "exampleTrans": "好的資訊要與朋友分享。", "diff": "medium" },
  { "word": "저장하다", "pos": "v.", "trans": "儲存 / 保存", "example": "파일을 클라우드에 저장했어요.", "exampleTrans": "把檔案儲存到雲端了。", "diff": "medium" },
  { "word": "삭제하다", "pos": "v.", "trans": "刪除", "example": "필요 없는 앱을 삭제했어요.", "exampleTrans": "刪除了不需要的 App。", "diff": "medium" },
  { "word": "충전하다", "pos": "v.", "trans": "充電 / 加值", "example": "배터리가 없어서 충전해야 해요.", "exampleTrans": "沒電了得充電。", "diff": "medium" },
  { "word": "다운로드", "pos": "n.", "trans": "下載", "example": "최신 영화를 다운로드 받았어요.", "exampleTrans": "下載了最新的電影。", "diff": "medium" },
  { "word": "업로드", "pos": "n.", "trans": "上傳", "example": "유튜브에 영상을 업로드했어요.", "exampleTrans": "把影片上傳到 YouTube 了。", "diff": "medium" },
  { "word": "비밀번호", "pos": "n.", "trans": "密碼", "example": "비밀번호를 자꾸 잊어버려요.", "exampleTrans": "老是忘記密碼。", "diff": "medium" },
  { "word": "아이디", "pos": "n.", "trans": "帳號 ID", "example": "로그인하려면 아이디를 입력하세요.", "exampleTrans": "想登入的話請輸入帳號。", "diff": "medium" },
  { "word": "와이파이", "pos": "n.", "trans": "Wi-Fi", "example": "여기 와이파이 비밀번호가 뭐예요?", "exampleTrans": "這裡的 Wi-Fi 密碼是什麼？", "diff": "medium" },
  { "word": "신호", "pos": "n.", "trans": "信號 / 紅綠燈", "example": "신호를 기다리고 있어요.", "exampleTrans": "正在等紅綠燈。", "diff": "medium" },
  { "word": "교통사고", "pos": "n.", "trans": "交通事故", "example": "길이 막히는 걸 보니 교통사고가 났나 봐요.", "exampleTrans": "路這麼塞，看來是出車禍了。", "diff": "medium" },
  { "word": "지각하다", "pos": "v.", "trans": "遲到", "example": "늦잠을 자서 학교에 지각했어요.", "exampleTrans": "因為睡懶覺上學遲到了。", "diff": "medium" },
  { "word": "결석하다", "pos": "v.", "trans": "缺席 / 曠課", "example": "아파서 학교에 결석했어요.", "exampleTrans": "因為生病沒去上學。", "diff": "medium" },
  { "word": "방학", "pos": "n.", "trans": "放假 (學生)", "example": "기다리고 기다리던 여름 방학이에요.", "exampleTrans": "盼了又盼的暑假終於到了。", "diff": "medium" },
  { "word": "졸업하다", "pos": "v.", "trans": "畢業", "example": "드디어 대학교를 졸업했어요.", "exampleTrans": "終於大學畢業了。", "diff": "medium" },
  { "word": "입학하다", "pos": "v.", "trans": "入學", "example": "초등학교에 입학하는 조카가 귀여워요.", "exampleTrans": "要上小學的侄子很可愛。", "diff": "medium" },
  { "word": "성적", "pos": "n.", "trans": "成績", "example": "이번 기말고사 성적이 잘 나왔어요.", "exampleTrans": "這次期末考成績不錯。", "diff": "medium" },
  { "word": "장학금", "pos": "n.", "trans": "獎學金", "example": "열심히 공부해서 장학금을 받았어요.", "exampleTrans": "努力學習領到了獎學金。", "diff": "medium" },
  { "word": "동아리", "pos": "n.", "trans": "社團", "example": "댄스 동아리에 가입했어요.", "exampleTrans": "加入了舞蹈社團。", "diff": "medium" },
  { "word": "과제", "pos": "n.", "trans": "課題 / 任務", "example": "팀별 과제를 수행하고 있어요.", "exampleTrans": "正在進行小組課題。", "diff": "medium" },
  { "word": "자격증", "pos": "n.", "trans": "證照", "example": "컴퓨터 자격증을 따려고 해요.", "exampleTrans": "打算考電腦證照。", "diff": "medium" },
  { "word": "공무원", "pos": "n.", "trans": "公務員", "example": "공무원 시험을 준비하는 사람이 많아요.", "exampleTrans": "準備公務員考試的人很多。", "diff": "medium" },
  { "word": "취직하다", "pos": "v.", "trans": "就職", "example": "대기업에 취직하게 되어 기뻐요.", "exampleTrans": "很高興能進大企業工作。", "diff": "medium" },
  { "word": "퇴직하다", "pos": "v.", "trans": "退職 / 退休", "example": "아버지는 작년에 정년 퇴직하셨어요.", "exampleTrans": "爸爸去年屆齡退休了。", "diff": "medium" },
  { "word": "전문가", "pos": "n.", "trans": "專家", "example": "그는 이 분야의 최고 전문가예요.", "exampleTrans": "他是這個領域最頂尖的專家。", "diff": "medium" },
  { "word": "성취감", "pos": "n.", "trans": "成就感", "example": "일을 마친 후 성취감을 느껴요.", "exampleTrans": "完成工作後感到很有成就感。", "diff": "medium" },
  { "word": "보람", "pos": "n.", "trans": "意義 / 價值感", "example": "봉사활동은 정말 보람 있는 일이에요.", "exampleTrans": "做志工真的是很有意義的事。", "diff": "medium" },
  { "word": "경험하다", "pos": "v.", "trans": "經驗 / 經歷", "example": "다양한 문화를 경험하는 게 좋아요.", "exampleTrans": "多經歷不同的文化比較好。", "diff": "medium" },
  { "word": "상상하다", "pos": "v.", "trans": "想像", "example": "미래의 도시를 상상해 보세요.", "exampleTrans": "請想像未來的城市。", "diff": "medium" },
  { "word": "표현하다", "pos": "v.", "trans": "表現 / 表達", "example": "자신의 생각을 자유롭게 표현하세요.", "exampleTrans": "請自由地表達自己的想法。", "diff": "medium" },
  { "word": "응원하다", "pos": "v.", "trans": "應援 / 加油", "example": "우리 팀을 열심히 응원해요.", "exampleTrans": "賣力為我們隊加油。", "diff": "medium" },
  { "word": "축하하다", "pos": "v.", "trans": "祝賀", "example": "생일을 진심으로 축하해요.", "exampleTrans": "衷心祝你生日快樂。", "diff": "medium" },
  { "word": "환영하다", "pos": "v.", "trans": "歡迎", "example": "신입생 여러분을 환영합니다.", "exampleTrans": "歡迎各位新生。", "diff": "medium" },
  { "word": "방문하다", "pos": "v.", "trans": "訪問 / 拜訪", "example": "할머니 댁을 방문했어요.", "exampleTrans": "拜訪了奶奶家。", "diff": "medium" },
  { "word": "초대하다", "pos": "v.", "trans": "招待 / 邀請", "example": "집들이에 친구들을 초대했어요.", "exampleTrans": "邀請朋友們來入厝趴。", "diff": "medium" },
  { "word": "참석하다", "pos": "v.", "trans": "出席", "example": "결혼식에 꼭 참석해 주세요.", "exampleTrans": "請務必出席婚禮。", "diff": "medium" },
  { "word": "거절하다", "pos": "v.", "trans": "拒絕", "example": "부탁을 정중히 거절했어요.", "exampleTrans": "鄭重地拒絕了請求。", "diff": "medium" },
  { "word": "부탁하다", "pos": "v.", "trans": "拜託", "example": "도움이 필요해서 부탁 좀 드릴게요.", "exampleTrans": "因為需要幫忙，想拜託您一件事。", "diff": "medium" },
  { "word": "신청하다", "pos": "v.", "trans": "申請", "example": "수강 신청 기간을 확인하세요.", "exampleTrans": "請確認選課申請期間。", "diff": "medium" },
  { "word": "예약하다", "pos": "v.", "trans": "預約", "example": "식당을 미리 예약해 뒀어요.", "exampleTrans": "已經預約好餐廳了。", "diff": "medium" },
  { "word": "취소하다", "pos": "v.", "trans": "取消", "example": "갑자기 일이 생겨서 예약을 취소했어요.", "exampleTrans": "突然有事所以取消了預約。", "diff": "medium" },
  { "word": "연기하다", "pos": "v.", "trans": "延期 / 演戲", "example": "약속 시간을 내일로 연기했어요.", "exampleTrans": "把約定時間改到明天了。", "diff": "medium" },
  { "word": "변경하다", "pos": "v.", "trans": "變更 / 修改", "example": "비행기 티켓 날짜를 변경했어요.", "exampleTrans": "更改了機票日期。", "diff": "medium" },
  { "word": "확인하다", "pos": "v.", "trans": "確認", "example": "메일을 보냈으니 확인해 보세요.", "exampleTrans": "寄了郵件，請確認一下。", "diff": "medium" },
  { "word": "검사하다", "pos": "v.", "trans": "檢查", "example": "시력 검사를 하러 안과에 가요.", "exampleTrans": "去眼科做視力檢查。", "diff": "medium" },
  { "word": "조사하다", "pos": "v.", "trans": "調查", "example": "설문 조사를 실시하고 있어요.", "exampleTrans": "正在實施問卷調查。", "diff": "medium" },
  { "word": "분석하다", "pos": "v.", "trans": "分析", "example": "데이터를 철저히 분석해야 해요.", "exampleTrans": "得徹底分析數據。", "diff": "medium" },
  { "word": "발표하다", "pos": "v.", "trans": "發表 / 公布", "example": "새로운 프로젝트 결과를 발표해요.", "exampleTrans": "發表新專案的結果。", "diff": "medium" },
  { "word": "설명하다", "pos": "v.", "trans": "說明 / 解釋", "example": "사용 방법을 자세히 설명해 드릴게요.", "exampleTrans": "我會詳細說明使用方法。", "diff": "medium" },
  { "word": "비교하다", "pos": "v.", "trans": "比較", "example": "남과 비교하지 말고 자신을 사랑하세요.", "exampleTrans": "不要跟別人比較，愛你自己吧。", "diff": "medium" },
  { "word": "정리하다", "pos": "v.", "trans": "整理", "example": "방이 너무 어지러워서 정리했어요.", "exampleTrans": "房間太亂了所以整理了一下。", "diff": "medium" },
  { "word": "준비하다", "pos": "v.", "trans": "準備", "example": "아침 식사를 준비하고 있어요.", "exampleTrans": "正在準備早餐。", "diff": "medium" },
  { "word": "관리하다", "pos": "v.", "trans": "管理", "example": "건강을 위해 식단을 관리해요.", "exampleTrans": "為了健康而管理飲食。", "diff": "medium" },
  { "word": "보호하다", "pos": "v.", "trans": "保護", "example": "피부를 자외선으로부터 보호해요.", "exampleTrans": "保護皮膚免受紫外線傷害。", "diff": "medium" },
  { "word": "유지하다", "pos": "v.", "trans": "維持", "example": "적정 체중을 유지하는 게 좋아요.", "exampleTrans": "維持適當體重比較好。", "diff": "medium" },
  { "word": "발전하다", "pos": "v.", "trans": "發展", "example": "우리 동네가 참 많이 발전했네요.", "exampleTrans": "我們這區發展了真多呢。", "diff": "medium" },
  { "word": "개선하다", "pos": "v.", "trans": "改善", "example": "불편한 점을 개선해 나갈게요.", "exampleTrans": "會改善不便的地方。", "diff": "medium" },
  { "word": "해결하다", "pos": "v.", "trans": "解決", "example": "문제를 스스로 해결하는 능력이 중요해요.", "exampleTrans": "自己解決問題的能力很重要。", "diff": "medium" },
  { "word": "도전하다", "pos": "v.", "trans": "挑戰", "example": "어려운 일에 도전하는 모습이 멋져요.", "exampleTrans": "挑戰難事的樣子很帥。", "diff": "medium" },
  { "word": "성취하다", "pos": "v.", "trans": "成就 / 達成", "example": "꿈을 성취하기 위해 최선을 다해요.", "exampleTrans": "為達成夢想而盡力。", "diff": "medium" },
  { "word": "발휘하다", "pos": "v.", "trans": "發揮", "example": "자신의 실력을 마음껏 발휘하세요.", "exampleTrans": "請盡情發揮您的實力。", "diff": "medium" },
  { "word": "집중하다", "pos": "v.", "trans": "集中 / 專注", "example": "수업에 집중하느라 시간 가는 줄 몰랐어요.", "exampleTrans": "因為專注上課而忘了時間流逝。", "diff": "medium" },
  { "word": "포함하다", "pos": "v.", "trans": "包含", "example": "봉사료가 포함된 가격입니다.", "exampleTrans": "這是包含服務費的價格。", "diff": "medium" },
  { "word": "제외하다", "pos": "v.", "trans": "排除 / 扣除", "example": "주말을 제외하고 3일 걸려요.", "exampleTrans": "扣除週末需要三天。", "diff": "medium" },
  { "word": "추가하다", "pos": "v.", "trans": "追加 / 增加", "example": "반찬 좀 더 추가해 주세요.", "exampleTrans": "請幫我多加點小菜。", "diff": "medium" },
  { "word": "생산하다", "pos": "v.", "trans": "生產", "example": "공장에서 자동차를 생산해요.", "exampleTrans": "工廠在生產汽車。", "diff": "medium" },
  { "word": "소비하다", "pos": "v.", "trans": "消費", "example": "에너지를 절약하고 불필요한 소비를 줄여요.", "exampleTrans": "節約能源並減少不必要的消費。", "diff": "medium" },
  { "word": "판매하다", "pos": "v.", "trans": "販賣", "example": "인터넷에서 수제 비누를 판매해요.", "exampleTrans": "在網路上賣手工皂。", "diff": "medium" },
  { "word": "수출하다", "pos": "v.", "trans": "出口", "example": "한국은 반도체를 많이 수출해요.", "exampleTrans": "韓國出口很多半導體。", "diff": "medium" },
  { "word": "수입하다", "pos": "v.", "trans": "進口", "example": "외국에서 과일을 수입해요.", "exampleTrans": "從國外進口水果。", "diff": "medium" },
  { "word": "인정하다", "pos": "v.", "trans": "認定 / 承認", "example": "자신의 실수를 솔직히 인정하세요.", "exampleTrans": "請坦率承認自己的錯誤。", "diff": "medium" },
  { "word": "존중하다", "pos": "v.", "trans": "尊重", "example": "상대방의 의견을 존중해야 합니다.", "exampleTrans": "必須尊重對方的意見。", "diff": "medium" },
  { "word": "신뢰하다", "pos": "v.", "trans": "信賴", "example": "오랜 친구라 깊이 신뢰해요.", "exampleTrans": "因為是老朋友所以深信不疑。", "diff": "medium" },
  { "word": "의심하다", "pos": "v.", "trans": "懷疑", "example": "근거 없이 남을 의심하지 마세요.", "exampleTrans": "請不要在沒有根據的情況下懷疑別人。", "diff": "medium" },
  { "word": "배려하다", "pos": "v.", "trans": "體諒 / 關照", "example": "주변 사람들을 배려하는 마음이 예뻐요.", "exampleTrans": "體諒周圍的人的心意很美。", "diff": "medium" },
  { "word": "양보하다", "pos": "v.", "trans": "讓步 / 讓座", "example": "노약자에게 자리를 양보하세요.", "exampleTrans": "請讓座給老弱婦孺。", "diff": "medium" },
  { "word": "협력하다", "pos": "v.", "trans": "協力 / 合作", "example": "팀원들과 긴밀히 협력하고 있어요.", "exampleTrans": "正與團隊成員緊密合作。", "diff": "medium" },
  { "word": "화해하다", "pos": "v.", "trans": "和解", "example": "싸운 친구와 드디어 화해했어요.", "exampleTrans": "終於和吵架的朋友和解了。", "diff": "medium" },
  { "word": "이해하다", "pos": "v.", "trans": "理解", "example": "문제를 완전히 이해할 때까지 질문하세요.", "exampleTrans": "請提問直到完全理解問題為止。", "diff": "medium" },
  { "word": "용서하다", "pos": "v.", "trans": "原諒", "example": "진심으로 사과하면 용서해 줄게요.", "exampleTrans": "只要真心道歉我就原諒你。", "diff": "medium" },
  { "word": "기대하다", "pos": "v.", "trans": "期待", "example": "이번 여행이 정말 기대돼요.", "exampleTrans": "這次旅行真的很讓人期待。", "diff": "medium" },
  { "word": "걱정하다", "pos": "v.", "trans": "擔心", "example": "아무 일 없을 테니 너무 걱정하지 마세요.", "exampleTrans": "不會有事的，請不要太擔心。", "diff": "medium" },
  { "word": "결심하다", "pos": "v.", "trans": "下定決心", "example": "새해부터 운동하기로 결심했어요.", "exampleTrans": "下定決心從新年開始運動。", "diff": "medium" },
  { "word": "결정하다", "pos": "v.", "trans": "決定", "example": "저녁 메뉴를 아직 못 결정했어요.", "exampleTrans": "還沒決定好晚餐菜單。", "diff": "medium" },
  { "word": "고민하다", "pos": "v.", "trans": "苦惱 / 煩惱", "example": "살까 말까 고민 중이에요.", "exampleTrans": "正在煩惱要不要買。", "diff": "medium" },
  { "word": "반성하다", "pos": "v.", "trans": "反省", "example": "자신의 행동을 깊이 반성하고 있어요.", "exampleTrans": "正在深度反省自己的行為。", "diff": "medium" },
  { "word": "후회하다", "pos": "v.", "trans": "後悔", "example": "그때 그 말을 하지 말걸 후회해요.", "exampleTrans": "後悔那時不該說那句話。", "diff": "medium" },
  { "word": "인상적이다", "pos": "adj.", "trans": "印象深刻的", "example": "그 영화의 마지막 장면이 정말 인상적이었어요.", "exampleTrans": "那部電影的最後一個鏡頭真的很讓人印象深刻。", "diff": "hard" },
  { "word": "효과적이다", "pos": "adj.", "trans": "有效的", "example": "이 약은 감기에 아주 효과적이에요.", "exampleTrans": "這藥對感冒非常有效。", "diff": "hard" },
  { "word": "창의적이다", "pos": "adj.", "trans": "有創意的", "example": "그의 아이디어는 항상 창의적이에요.", "exampleTrans": "他的點子總是很具有創意。", "diff": "hard" },
  { "word": "합리적이다", "pos": "adj.", "trans": "合理的", "example": "가격이 매우 합리적이라 인기가 많아요.", "exampleTrans": "因為價格非常合理，所以很受歡迎。", "diff": "hard" },
  { "word": "성실하다", "pos": "adj.", "trans": "誠實 / 勤奮", "example": "그는 성실한 태도로 모두에게 인정받아요.", "exampleTrans": "他憑著勤奮的態度得到大家的認可。", "diff": "hard" },
  { "word": "겸손하다", "pos": "adj.", "trans": "謙虛", "example": "실력이 뛰어나지만 매우 겸손해요.", "exampleTrans": "實力雖然出眾，但非常謙虛。", "diff": "hard" },
  { "word": "친절하다", "pos": "adj.", "trans": "親切", "example": "그 점원은 손님들에게 항상 친절해요.", "exampleTrans": "那個店員對客人總是很親切。", "diff": "hard" },
  { "word": "정직하다", "pos": "adj.", "trans": "正直 / 誠實", "example": "어떠한 상황에서도 정직하게 행동하세요.", "exampleTrans": "在任何情況下請正直地行動。", "diff": "hard" },
  { "word": "당당하다", "pos": "adj.", "trans": "堂堂正正 / 自信", "example": "자신의 주장을 당당하게 밝히세요.", "exampleTrans": "請堂堂正正地表明自己的主張。", "diff": "hard" },
  { "word": "꼼꼼하다", "pos": "adj.", "trans": "仔細 / 細心", "example": "서류를 꼼꼼하게 검토했어요.", "exampleTrans": "仔細檢閱了文件。", "diff": "hard" },
  { "word": "냉정하다", "pos": "adj.", "trans": "冷靜 / 冷酷", "example": "때로는 냉정한 판단이 필요할 때가 있어요.", "exampleTrans": "有時需要冷靜的判斷。", "diff": "hard" },
  { "word": "침착하다", "pos": "adj.", "trans": "沉著 / 冷靜", "example": "위기 상황에서도 침착함을 잃지 마세요.", "exampleTrans": "即便在危機狀況下也請不要失去沉著。", "diff": "hard" },
  { "word": "신중하다", "pos": "adj.", "trans": "慎重", "example": "그는 말 한마디도 매우 신중하게 해요.", "exampleTrans": "他連說一句話都非常慎重。", "diff": "hard" },
  { "word": "단호하다", "pos": "adj.", "trans": "斷然 / 果斷", "example": "잘못된 일에는 단호하게 대처해야 해요.", "exampleTrans": "對錯誤的事情必須果斷處理。", "diff": "hard" },
  { "word": "긍정적이다", "pos": "adj.", "trans": "積極的 / 肯定的", "example": "무슨 일이든 긍정적으로 생각하세요.", "exampleTrans": "不論什麼事請都積極思考。", "diff": "hard" },
  { "word": "부정적이다", "pos": "adj.", "trans": "消極的 / 否定的", "example": "비판만 하는 부정적인 태도는 좋지 않아요.", "exampleTrans": "只會批評的消極態度並不好。", "diff": "hard" },
  { "word": "적극적이다", "pos": "adj.", "trans": "積極的", "example": "그는 무슨 일이든 적극적으로 참여해요.", "exampleTrans": "他對任何事都積極參與。", "diff": "hard" },
  { "word": "소극적이다", "pos": "adj.", "trans": "消極的 / 被動的", "example": "성격이 소극적이라 나서기를 꺼려해요.", "exampleTrans": "因為性格被動，所以不願意出頭。", "diff": "hard" },
  { "word": "낙천적이다", "pos": "adj.", "trans": "樂觀的", "example": "낙천적인 사람들과 있으면 기분이 좋아져요.", "exampleTrans": "和樂觀的人在一起心情會變好。", "diff": "hard" },
  { "word": "현실적이다", "pos": "adj.", "trans": "現實的", "example": "꿈만 꾸지 말고 현실적인 대안을 찾으세요.", "exampleTrans": "不要只做夢，請尋找現實的替代方案。", "diff": "hard" },
  { "word": "이상적이다", "pos": "adj.", "trans": "理想的", "example": "이곳은 살기에 아주 이상적인 환경이에요.", "exampleTrans": "這裡是非常理想的居住環境。", "diff": "hard" },
  { "word": "객관적이다", "pos": "adj.", "trans": "客觀的", "example": "자신의 감정을 배제하고 객관적으로 판단하세요.", "exampleTrans": "排除自己的感情，請客觀判斷。", "diff": "hard" },
  { "word": "주관적이다", "pos": "adj.", "trans": "主觀的", "example": "이건 제 주관적인 생각일 뿐이에요.", "exampleTrans": "這只是我個人的主觀想法而已。", "diff": "hard" },
  { "word": "상대적이다", "pos": "adj.", "trans": "相對的", "example": "행복은 주관적이고 상대적인 개념이에요.", "exampleTrans": "幸福是主觀且相對的概念。", "diff": "hard" },
  { "word": "절대적이다", "pos": "adj.", "trans": "絕對的", "example": "건강을 유지하는 게 절대적으로 중요해요.", "exampleTrans": "維持健康是絕對重要的事。", "diff": "hard" },
  { "word": "필수적이다", "pos": "adj.", "trans": "必不可少的", "example": "비타민은 우리 몸에 필수적인 영양소예요.", "exampleTrans": "維生素是我們身體必不可少的營養素。", "diff": "hard" },
  { "word": "선택적이다", "pos": "adj.", "trans": "選擇性的", "example": "이건 필수가 아닌 선택적인 사항입니다.", "exampleTrans": "這不是必填項，是選擇性的事項。", "diff": "hard" },
  { "word": "일시적이다", "pos": "adj.", "trans": "暫時的", "example": "이 증상은 일시적인 현상일 뿐이에요.", "exampleTrans": "這個症狀只是暫時的現象而已。", "diff": "hard" },
  { "word": "지속적이다", "pos": "adj.", "trans": "持續的", "example": "성공을 위해서는 지속적인 노력이 필요해요.", "exampleTrans": "為了成功需要持續的努力。", "diff": "hard" },
  { "word": "안정적이다", "pos": "adj.", "trans": "穩定的", "example": "그는 안정적인 직장을 다니고 싶어해요.", "exampleTrans": "他想找一份穩定的工作。", "diff": "hard" },
  { "word": "불안정하다", "pos": "adj.", "trans": "不穩定的", "example": "요즘 경제 상황이 매우 불안정해요.", "exampleTrans": "最近經濟狀況非常不穩定。", "diff": "hard" },
  { "word": "심각하다", "pos": "adj.", "trans": "嚴重的", "example": "환경 문제가 갈수록 심각해지고 있어요.", "exampleTrans": "環境問題正日益嚴重。", "diff": "hard" },
  { "word": "간단하다", "pos": "adj.", "trans": "簡單的", "example": "설명이 아주 간단해서 이해하기 쉬웠어요.", "exampleTrans": "說明非常簡單，所以很容易理解。", "diff": "hard" },
  { "word": "복잡하다", "pos": "adj.", "trans": "複雜的", "example": "길이 너무 복잡해서 길을 잃었어요.", "exampleTrans": "路太複雜了所以迷路了。", "diff": "hard" },
  { "word": "당연하다", "pos": "adj.", "trans": "理所當然的", "example": "노력하면 성공하는 건 당연한 결과예요.", "exampleTrans": "努力後成功是理所當然的結果。", "diff": "hard" },
  { "word": "불가능하다", "pos": "adj.", "trans": "不可能的", "example": "포기하지 않는다면 불가능은 없어요.", "exampleTrans": "只要不放棄就沒有不可能的事。", "diff": "hard" },
  { "word": "가능하다", "pos": "adj.", "trans": "可能的", "example": "당일 배송이 가능한가요?", "exampleTrans": "可以當天配送嗎？", "diff": "hard" },
  { "word": "충분하다", "pos": "adj.", "trans": "充分的", "example": "시간이 충분하니 천천히 하세요.", "exampleTrans": "時間很充分，請慢慢來。", "diff": "hard" },
  { "word": "부족하다", "pos": "adj.", "trans": "不足的", "example": "실력이 부족해서 더 연습해야 해요.", "exampleTrans": "實力不足，所以得再多練習。", "diff": "hard" },
  { "word": "귀중하다", "pos": "adj.", "trans": "珍貴的", "example": "귀중한 시간을 내주셔서 감사합니다.", "exampleTrans": "謝謝您抽出寶貴的時間。", "diff": "hard" },
  { "word": "소중하다", "pos": "adj.", "trans": "珍視的 / 寶貴的", "example": "가족은 저에게 가장 소중한 존재예요.", "exampleTrans": "家人對我來說是最珍貴的存在。", "diff": "hard" },
  { "word": "특별하다", "pos": "adj.", "trans": "特別的", "example": "오늘은 저에게 아주 특별한 날이에요.", "exampleTrans": "今天對我來說是非常特別的日子。", "diff": "hard" },
  { "word": "평범하다", "pos": "adj.", "trans": "平凡的", "example": "평범한 일상 속에서 행복을 찾아요.", "exampleTrans": "在平凡的日常中尋找幸福。", "diff": "hard" },
  { "word": "다양하다", "pos": "adj.", "trans": "多樣的", "example": "백화점에 다양한 상품이 진열되어 있어요.", "exampleTrans": "百貨公司陳列著多樣的商品。", "diff": "hard" },
  { "word": "일정하다", "pos": "adj.", "trans": "一定的 / 恆定的", "example": "규칙적이고 일정한 생활을 유지하세요.", "exampleTrans": "請保持規律且恆定的生活。", "diff": "hard" },
  { "word": "풍부하다", "pos": "adj.", "trans": "豐富的", "example": "그는 경험이 매우 풍부한 베테랑이에요.", "exampleTrans": "他是位經驗非常豐富的老手。", "diff": "hard" },
  { "word": "부족하다", "pos": "adj.", "trans": "缺乏 / 貧乏", "example": "영양소가 부족하면 면역력이 떨어져요.", "exampleTrans": "如果缺乏營養，免疫力會下降。", "diff": "hard" },
  { "word": "확실하다", "pos": "adj.", "trans": "確定的 / 明確的", "example": "그 정보가 확실한지 다시 확인해 보세요.", "exampleTrans": "請再次確認那項資訊是否正確。", "diff": "hard" },
  { "word": "불확실하다", "pos": "adj.", "trans": "不確定的", "example": "미래는 언제나 불확실하지만 희망은 있어요.", "exampleTrans": "未來雖然總是不確定的，但依然有希望。", "diff": "hard" },
  { "word": "우연히", "pos": "adv.", "trans": "偶然地", "example": "길에서 우연히 옛 친구를 만났어요.", "exampleTrans": "在路上偶然遇到了老朋友。", "diff": "hard" },
  { "word": "갑자기", "pos": "adv.", "trans": "突然地", "example": "하늘이 어두워지더니 갑자기 비가 왔어요.", "exampleTrans": "天空變暗後突然下雨了。", "diff": "hard" },
  { "word": "드디어", "pos": "adv.", "trans": "終於", "example": "드디어 제가 원하던 회사에 합격했어요.", "exampleTrans": "終於錄取了我想要的公車。", "diff": "hard" },
  { "word": "솔직히", "pos": "adv.", "trans": "坦白說", "example": "솔직히 말해서 그 제안은 별로예요.", "exampleTrans": "坦白說，那個提議不怎麼樣。", "diff": "hard" },
  { "word": "다행히", "pos": "adv.", "trans": "幸好", "example": "사고가 났지만 다행히 다친 사람은 없어요.", "exampleTrans": "出了車禍，但幸好沒人受傷。", "diff": "hard" },
  { "word": "오히려", "pos": "adv.", "trans": "反而", "example": "도와주려던 게 오히려 방해가 되었네요.", "exampleTrans": "本想幫忙的結果反而成了妨礙呢。", "diff": "hard" },
  { "word": "과연", "pos": "adv.", "trans": "果然 / 難道", "example": "과연 소문대로 그 영화는 대단했어요.", "exampleTrans": "果然如傳聞所言，那部電影很棒。", "diff": "hard" },
  { "word": "설마", "pos": "adv.", "trans": "該不會 / 難道", "example": "설마 그가 우리를 속였을까요?", "exampleTrans": "該不會他騙了我們吧？", "diff": "hard" },
  { "word": "아마", "pos": "adv.", "trans": "大概 / 也許", "example": "아마 내일은 날씨가 맑을 거예요.", "exampleTrans": "明天大概會是晴天。", "diff": "hard" },
  { "word": "반드시", "pos": "adv.", "trans": "務必 / 一定", "example": "이 약속은 반드시 지켜야 합니다.", "exampleTrans": "這個約定務必得守住。", "diff": "hard" },
  { "word": "절대로", "pos": "adv.", "trans": "絕對 (不)", "example": "그 일은 절대로 잊지 못할 거예요.", "exampleTrans": "那件事絕對忘不了。", "diff": "hard" },
  { "word": "함부로", "pos": "adv.", "trans": "隨便 / 妄為", "example": "쓰레기를 함부로 버리지 마세요.", "exampleTrans": "請不要亂丟垃圾。", "diff": "hard" },
  { "word": "겨우", "pos": "adv.", "trans": "好不容易 / 僅僅", "example": "막차를 겨우 탔어요.", "exampleTrans": "好不容易搭上了末班車。", "diff": "hard" },
  { "word": "미리", "pos": "adv.", "trans": "預先 / 事先", "example": "중요한 정보는 미리 메모해 두세요.", "exampleTrans": "重要的資訊請事先備註下來。", "diff": "hard" },
  { "word": "이미", "pos": "adv.", "trans": "已經", "example": "기차는 이미 떠났어요.", "exampleTrans": "火車已經開走了。", "diff": "hard" },
  { "word": "금방", "pos": "adv.", "trans": "馬上 / 剛才", "example": "숙제 금방 끝내고 놀러 갈게요.", "exampleTrans": "馬上做完作業就去玩。", "diff": "hard" },
  { "word": "방금", "pos": "adv.", "trans": "剛才", "example": "방금 도착했으니까 조금만 기다려 줘.", "exampleTrans": "剛到而已，請再等一下。", "diff": "hard" },
  { "word": "자꾸", "pos": "adv.", "trans": "老是 / 頻繁地", "example": "모르는 번호로 자꾸 전화가 와요.", "exampleTrans": "老是有陌生號碼打電話過來。", "diff": "hard" },
  { "word": "종종", "pos": "adv.", "trans": "時常 / 偶爾", "example": "퇴근 후에 종종 서점에 가요.", "exampleTrans": "下班後偶爾會去書店。", "diff": "hard" },
  { "word": "가끔", "pos": "adv.", "trans": "偶爾", "example": "가끔 옛날 생각이 날 때가 있어요.", "exampleTrans": "偶爾會想起以前的事。", "diff": "hard" },
  { "word": "전혀", "pos": "adv.", "trans": "完全不", "example": "그 사실에 대해서는 전혀 몰랐어요.", "exampleTrans": "關於那個事實完全不知情。", "diff": "hard" },
  { "word": "별로", "pos": "adv.", "trans": "不怎麼 / 普通", "example": "어제 본 영화는 별로 재미없었어요.", "exampleTrans": "昨天看的電影不怎麼有趣。", "diff": "hard" },
  { "word": "특히", "pos": "adv.", "trans": "特別是", "example": "저는 과일을 좋아하는데 특히 사과를 좋아해요.", "exampleTrans": "我喜歡水果，特別是蘋果。", "diff": "hard" },
  { "word": "매우", "pos": "adv.", "trans": "非常", "example": "상황이 매우 긴박하게 돌아가고 있어요.", "exampleTrans": "情況正變得非常緊迫。", "diff": "hard" },
  { "word": "꽤", "pos": "adv.", "trans": "相當", "example": "한국어 실력이 꽤 늘었네요.", "exampleTrans": "韓文實力進步相當多呢。", "diff": "hard" },
  { "word": "상당히", "pos": "adv.", "trans": "相當地 / 頗為", "example": "문제가 상당히 까다롭네요.", "exampleTrans": "問題頗為棘手呢。", "diff": "hard" },
  { "word": "엄청", "pos": "adv.", "trans": "超級 (口語)", "example": "오늘 날씨 엄청 춥네요.", "exampleTrans": "今天天氣超級冷呢。", "diff": "hard" },
  { "word": "무척", "pos": "adv.", "trans": "非常 / 極其", "example": "할머니가 무척 보고 싶어요.", "exampleTrans": "非常想念奶奶。", "diff": "hard" },
  { "word": "훨씬", "pos": "adv.", "trans": "得多 / 更加", "example": "이게 저것보다 훨씬 예뻐요.", "exampleTrans": "這個比那個漂亮得多。", "diff": "hard" },
  { "word": "점점", "pos": "adv.", "trans": "逐漸", "example": "날씨가 점점 따뜻해지고 있어요.", "exampleTrans": "天氣正逐漸變暖。", "diff": "hard" },
  { "word": "점차", "pos": "adv.", "trans": "漸漸 / 逐步", "example": "경기가 점차 회복될 전망입니다.", "exampleTrans": "預計景氣會逐步恢復。", "diff": "hard" },
  { "word": "끊임없이", "pos": "adv.", "trans": "不斷地", "example": "목표를 향해 끊임없이 도전하세요.", "exampleTrans": "請朝著目標不斷挑戰。", "diff": "hard" },
  { "word": "꾸준히", "pos": "adv.", "trans": "持續地 / 穩步地", "example": "매일 꾸준히 운동하는 게 중요해요.", "exampleTrans": "每天持續運動是很重要的。", "diff": "hard" },
  { "word": "부지런히", "pos": "adv.", "trans": "勤奮地", "example": "부지런히 일해서 성공하고 싶어요.", "exampleTrans": "想勤奮工作並獲得成功。", "diff": "hard" },
  { "word": "열심히", "pos": "adv.", "trans": "努力地", "example": "한국어를 열심히 공부해서 한국에 갈 거예요.", "exampleTrans": "會努力學習韓文然後去韓國。", "diff": "hard" },
  { "word": "자세히", "pos": "adv.", "trans": "詳細地", "example": "그 사건에 대해 자세히 말해 주세요.", "exampleTrans": "請詳細說明那起事件。", "diff": "hard" },
  { "word": "분명히", "pos": "adv.", "trans": "清晰地 / 明確地", "example": "자신의 의사를 분명히 전달하세요.", "exampleTrans": "請明確傳達自己的意思。", "diff": "hard" },
  { "word": "정확히", "pos": "adv.", "trans": "準確地", "example": "시간을 정확히 지켜 주세요.", "exampleTrans": "請準確守時。", "diff": "hard" },
  { "word": "확실히", "pos": "adv.", "trans": "確實地", "example": "어제보다 확실히 컨디션이 좋네요.", "exampleTrans": "狀態確實比昨天好呢。", "diff": "hard" },
  { "word": "당연히", "pos": "adv.", "trans": "當然", "example": "도움을 받았으면 당연히 고마워해야죠.", "exampleTrans": "得到幫助的話當然要心存感激。", "diff": "hard" },
  { "word": "어쩔 수 없이", "pos": "phrase", "trans": "無可奈何地", "example": "비가 와서 어쩔 수 없이 실내에서 놀았어요.", "exampleTrans": "因為下雨，無可奈何只好在室內玩。", "diff": "hard" },
  { "word": "간신히", "pos": "adv.", "trans": "勉強 / 差點沒...", "example": "시험에 간신히 합격했어요.", "exampleTrans": "勉強通過了考試。", "diff": "hard" },
  { "word": "일부러", "pos": "adv.", "trans": "故意地", "example": "화나게 하려고 일부러 그런 건 아니에요.", "exampleTrans": "並非故意要惹你生氣。", "diff": "hard" },
  { "word": "저절로", "pos": "adv.", "trans": "自動地 / 自然而然", "example": "문을 열었더니 찬 바람이 저절로 들어와요.", "exampleTrans": "一開門冷風就自動吹進來了。", "diff": "hard" },
  { "word": "억지로", "pos": "adv.", "trans": "勉強地 / 乾巴巴地", "example": "하기 싫은 일을 억지로 하지 마세요.", "exampleTrans": "請不要勉強做不想做的事。", "diff": "hard" },
  { "word": "무사히", "pos": "adv.", "trans": "平安地", "example": "여행을 마치고 무사히 돌아왔어요.", "exampleTrans": "結束旅行平安回來了。", "diff": "hard" },
  { "word": "급히", "pos": "adv.", "trans": "緊急地", "example": "급히 연락드릴 일이 생겼어요.", "exampleTrans": "發生了需要緊急聯絡的事情。", "diff": "hard" },
  { "word": "천천히", "pos": "adv.", "trans": "慢慢地", "example": "서두르지 말고 천천히 드세요.", "exampleTrans": "請不要著急，慢慢吃。", "diff": "hard" },
  { "word": "우연히", "pos": "adv.", "trans": "偶然地", "example": "서점에서 우연히 그를 마주쳤어요.", "exampleTrans": "在書店偶然遇見了他。", "diff": "hard" },
  { "word": "기꺼이", "pos": "adv.", "trans": "樂意地", "example": "도움이 된다면 기꺼이 도와드릴게요.", "exampleTrans": "如果有幫助的話，我很樂意幫忙。", "diff": "hard" },
  { "word": "진심으로", "pos": "adv.", "trans": "衷心地", "example": "친구의 성공을 진심으로 기뻐해 줬어요.", "exampleTrans": "衷心為朋友的成功感到高興。", "diff": "hard" },

  // --- Pro Advanced Batch: Abstract & Academic ---
  { "word": "고정관념", "pos": "n.", "trans": "刻板印象", "example": "고정관념에서 벗어나는 것이 필요해요.", "exampleTrans": "有必要擺脫刻板印象。", "diff": "pro" },
  { "word": "상호작용", "pos": "n.", "trans": "相互作用 / 互動", "example": "사람들 간의 상호작용이 사회를 만들어요.", "exampleTrans": "人與人之間的互動構成了社會。", "diff": "pro" },
  { "word": "인과관계", "pos": "n.", "trans": "因果關係", "example": "두 사건 사이의 인과관계를 밝혀내야 해요.", "exampleTrans": "得查明兩起事件之間的因果關係。", "diff": "pro" },
  { "word": "우선순위", "pos": "n.", "trans": "優先順序", "example": "일의 우선순위를 정해서 처리하세요.", "exampleTrans": "請排定工作的優先順序來處理。", "diff": "pro" },
  { "word": "가치관", "pos": "n.", "trans": "價值觀", "example": "서로 가치관이 달라서 갈등이 생겼어요.", "exampleTrans": "因為彼此價值觀不同而產生了衝突。", "diff": "pro" },
  { "word": "자아실현", "pos": "n.", "trans": "自我實現", "example": "직업을 통해 자아실현을 꿈꿔요.", "exampleTrans": "夢想透過職業來實現自我。", "diff": "pro" },
  { "word": "잠재력", "pos": "n.", "trans": "潛力", "example": "누구나 무한한 잠재력을 가지고 있어요.", "exampleTrans": "每個人都擁有無限的潛力。", "diff": "pro" },
  { "word": "타협하다", "pos": "v.", "trans": "妥協", "example": "현실과 적당히 타협하며 살아가요.", "exampleTrans": "與現實適當妥協地生活著。", "diff": "pro" },
  { "word": "극복하다", "pos": "v.", "trans": "克服", "example": "어려운 환경을 극복하고 성공했어요.", "exampleTrans": "克服了困苦的環境並獲得成功。", "diff": "pro" },
  { "word": "기여하다", "pos": "v.", "trans": "貢獻", "example": "지역 사회 발전에 기여하고 싶어요.", "exampleTrans": "想為區域社會發展做出貢獻。", "diff": "pro" },
  { "word": "실천하다", "pos": "v.", "trans": "實踐", "example": "계획만 세우지 말고 바로 실천하세요.", "exampleTrans": "不要只做計畫，請立即實踐。", "diff": "pro" },
  { "word": "비판하다", "pos": "v.", "trans": "批判", "example": "무조건적인 비난보다는 건전한 비판이 필요해요.", "exampleTrans": "比起無條件的指責，更需要健全的批判。", "diff": "pro" },
  { "word": "반영하다", "pos": "v.", "trans": "反映", "example": "소비자의 요구를 제품에 반영했어요.", "exampleTrans": "將消費者的需求反映在產品中。", "diff": "pro" },
  { "word": "축적하다", "pos": "v.", "trans": "蓄積 / 累積", "example": "오랜 시간 동안 지식을 축적해 왔어요.", "exampleTrans": "長久以來一直在累積知識。", "diff": "pro" },
  { "word": "추구하다", "pos": "v.", "trans": "追求", "example": "진정한 행복을 추구하며 살아요.", "exampleTrans": "追求真正的幸福地生活著。", "diff": "pro" },
  { "word": "확립하다", "pos": "v.", "trans": "確立", "example": "새로운 질서를 확립하는 것이 시급해요.", "exampleTrans": "確立新秩序是當務之急。", "diff": "pro" },
  { "word": "조성하다", "pos": "v.", "trans": "營造 / 建立", "example": "공포 분위기를 조성하지 마세요.", "exampleTrans": "請不要營造恐怖氣氛。", "diff": "pro" },
  { "word": "도출하다", "pos": "v.", "trans": "得出 / 推導", "example": "회의를 통해 합의점을 도출했어요.", "exampleTrans": "透過會議得出了共識。", "diff": "pro" },
  { "word": "상기시키다", "pos": "v.", "trans": "使想起 / 提醒", "example": "그 노래는 옛 추억을 상기시켜 줘요.", "exampleTrans": "那首歌勾起了我的舊回憶。", "diff": "pro" },
  { "word": "인지하다", "pos": "v.", "trans": "認知 / 察覺", "example": "상황의 심각성을 인지해야 합니다.", "exampleTrans": "必須察覺情況的嚴重性。", "diff": "pro" },
  { "word": "수용하다", "pos": "v.", "trans": "收容 / 接受", "example": "다른 문화의 장점을 적극적으로 수용해요.", "exampleTrans": "積極接受其他文化的優點。", "diff": "pro" },
  { "word": "배제하다", "pos": "v.", "trans": "排除", "example": "모든 가능성을 배제할 수는 없어요.", "exampleTrans": "不能排除所有的可能性。", "diff": "pro" },
  { "word": "보완하다", "pos": "v.", "trans": "補完 / 彌補", "example": "부족한 점을 보완해서 다시 제출할게요.", "exampleTrans": "會彌補不足之處後重新提交。", "diff": "pro" },
  { "word": "규제하다", "pos": "v.", "trans": "管制 / 限制", "example": "환경 오염을 줄이기 위해 규제를 강화해요.", "exampleTrans": "為了減少環保污染而強化管制。", "diff": "pro" },
  { "word": "장려하다", "pos": "v.", "trans": "獎勵 / 鼓勵", "example": "정부는 출산을 장려하는 정책을 펼쳐요.", "exampleTrans": "政府推行鼓勵生育的政策。", "diff": "pro" },
  { "word": "정당화하다", "pos": "v.", "trans": "正當化 / 辯解", "example": "자신의 실수를 정당화하려고 하지 마세요.", "exampleTrans": "請不要試圖將自己的錯誤正當化。", "diff": "pro" },
  { "word": "합리화하다", "pos": "v.", "trans": "合理化", "example": "게으름을 합리화하지 말고 부지런해지세요.", "exampleTrans": "不要將懶惰合理化，請勤奮起來。", "diff": "pro" },
  { "word": "객관화하다", "pos": "v.", "trans": "客觀化", "example": "자신의 감정을 객관화해서 바라보세요.", "exampleTrans": "請試著將自己的感情客觀化後觀察。", "diff": "pro" },
  { "word": "차별화하다", "pos": "v.", "trans": "差別化 / 區分", "example": "다른 브랜드와 차별화된 전략이 필요해요.", "exampleTrans": "需要與其他品牌區分開來的策略。", "diff": "pro" },
  { "word": "단순화하다", "pos": "v.", "trans": "單純化 / 簡化", "example": "복잡한 문제를 단순화해서 생각하세요.", "exampleTrans": "請將複雜的問題簡化思考。", "diff": "pro" },
  { "word": "일반화하다", "pos": "v.", "trans": "一般化 / 概括", "example": "하나의 사례로 전체를 일반화하면 안 돼요.", "exampleTrans": "不能用一個案例來概括全體。", "diff": "pro" },
  { "word": "전문화하다", "pos": "v.", "trans": "專業化", "example": "지식을 전문화해서 경쟁력을 키워요.", "exampleTrans": "將知識專業化以培養競爭力。", "diff": "pro" },
  { "word": "구체화하다", "pos": "v.", "trans": "具體化", "example": "추상적인 아이디어를 구체화해 보세요.", "exampleTrans": "請試著將抽象的點子具體化。", "diff": "pro" },
  { "word": "시각화하다", "pos": "v.", "trans": "視覺化", "example": "데이터를 그래프로 시각화했어요.", "exampleTrans": "將數據以圖表進行視覺化呈現。", "diff": "pro" },
  { "word": "표준화하다", "pos": "v.", "trans": "標準化", "example": "작업 공정을 표준화해서 효율을 높여요.", "exampleTrans": "將作業流程標準化以提高效率。", "diff": "pro" },
  { "word": "민주화", "pos": "n.", "trans": "民主化", "example": "한국의 민주화 운동은 대단한 역사예요.", "exampleTrans": "韓國的民主化運動是偉大的歷史。", "diff": "pro" },
  { "word": "산업화", "pos": "n.", "trans": "產業化 / 工業化", "example": "산업화로 인해 도시 인구가 급증했어요.", "exampleTrans": "因為工業化，城市人口急遽增加。", "diff": "pro" },
  { "word": "현대화", "pos": "n.", "trans": "現代化", "example": "전통 시장의 현대화 작업이 진행 중이에요.", "exampleTrans": "傳統市場的現代化工程正在進行中。", "diff": "pro" },
  { "word": "정보화", "pos": "n.", "trans": "資訊化", "example": "정보화 사회에서는 데이터가 큰 자산이에요.", "exampleTrans": "在資訊化社會中，數據是巨大的資產。", "diff": "pro" },
  { "word": "세계화", "pos": "n.", "trans": "世界化 / 全球化", "example": "세계화 시대에 발맞추어 나아가야 해요.", "exampleTrans": "得跟上全球化時代的步伐。", "diff": "pro" },
  { "word": "도시화", "pos": "n.", "trans": "都市化", "example": "급격한 도시화로 주택난이 심해졌어요.", "exampleTrans": "劇烈的都市化導致住宅短缺嚴重。", "diff": "pro" },
  { "word": "대중화", "pos": "n.", "trans": "大眾化 / 普及化", "example": "스마트폰의 대중화가 세상을 바꿨어요.", "exampleTrans": "智慧型手機的普及改變了世界。", "diff": "pro" }
];